CONTRIBUTING.md, INDEX.md, README.md
Adds a curated list of samples to the samples repo.
=> Samples index

veggieseasons/lib/screens/search.dart, veggieseasons/lib/widgets/search_bar.dart
FWIW, this is my first experience with text editing, so don't be afraid to suggest a refactor of how the SearchScreen and SearchBar widgets are splitting work.
=> Adds search screen to veggieseasons.

place_tracker/README.md
Add more description to the intro and add new sections: goals, important bits, caveat, and questions.
=> Add additional details to the place_tracker demo app README.

place_tracker/lib/place_map.dart
Added a button that toggles between different map types: satellite, terrain, hybrid, and normal.
=> Add map type toggle to place_tracker demo.

place_tracker/lib/place_details.dart, place_tracker/lib/place_map.dart, place_tracker/lib/stub_data.dart
Offers a better demonstration of the map in a list view.
=> Add stub reviews to the place details sheet. 

jsonexample/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, jsonexample/pubspec.yaml, shrine/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, shrine/lib/expanding_bottom_sheet.dart
Also adds a new project file created by Xcode.
=> Fixes Future<void> issue in Shrine.

INDEX.md
As discussed offline today with @RedBrogdon.
I added some other stuff there as well, such as mentioning about testing and Redux. [See the updated and rendered README here](https://github.com/flutter/samples/blob/bc27c859d0cc71df49b43a96cf4d48b3faa3de54/INDEX.md).
It turned a little lengthier than previous description - I'm open to feedback about this! It's totally OK for me to just leave it as it was before and only mention about the code sharing part. :-)
=> Mention that inKino is sharing code between web and mobile

INDEX.md
A simple todo app builds on BLoC pattern.
=> Adding WhatTodo app in Full apps

INDEX.md, README.md
Removes pre-1.0 note from README and tweaks some of the text in the curated index.
=> Updates to readme, index.

shrine/lib/app.dart, shrine/lib/login.dart, shrine/lib/supplemental/cut_corners_border.dart
@willlarche, you may recall the changes you helped me with just prior to #AskFlutter. This PR adds them to the actual repo for posterity
=> Adds some Shrine updates from Material team.

.travis.yml, jsonexample/pubspec.yaml, place_tracker/lib/app_model.dart, place_tracker/lib/place.dart, place_tracker/lib/place_details.dart, place_tracker/lib/place_list.dart, place_tracker/lib/place_map.dart, place_tracker/lib/place_tracker_app.dart, place_tracker/lib/stub_data.dart, place_tracker/test/widget_test.dart, platform_view_swift/lib/main.dart, platform_view_swift/pubspec.yaml, platform_view_swift/test/widgets_test.dart, travis_script.sh
Updates the Travis config for the repo, and makes small changes to place_tracker and platform_view_swift for formatting and analyzer issues.
=> Updates travis config to include place_tracker and platform_view_swift

INDEX.md
Adding Flutter Playground repository in How-to Collections
=> Adding Flutter Playground repository

INDEX.md
An extra conjunction has no function.
=> Removes extra 'because' in INDEX.md

veggieseasons/lib/screens/search.dart, veggieseasons/lib/widgets/search_bar.dart
Also renames some properties to bring them in line with conventions elsewhere in the app.
=> Adding "no results" display to search screen.

place_tracker/analysis_options.yaml, place_tracker/ios/Podfile, place_tracker/ios/Runner/AppDelegate.m, place_tracker/ios/Runner/Info.plist, place_tracker/lib/place_details.dart, place_tracker/lib/place_map.dart, place_tracker/pubspec.yaml
Updated the Google Maps article this morning to use the latest version of the google_maps_flutter plugin. While I was doing this, wanted to do a quick re-vamp on the sample app as well.
=> Update Place Tracker to use latest version of plugin.

veggieseasons/ios/Runner.xcodeproj/project.pbxproj
you're gonna need this to profile the app (since you created the project earlier on)
=> add profile xcode configuration

veggieseasons/lib/data/local_veggie_provider.dart
See https://www.californiaavocado.com/blog/avocado-fruit-or-vegetable
=> Small text correction

place_tracker/ios/Podfile.lock, place_tracker/ios/Runner.xcodeproj/project.pbxproj, place_tracker/ios/Runner.xcworkspace/contents.xcworkspacedata, place_tracker/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, place_tracker/pubspec.lock, place_tracker/pubspec.yaml
We were getting an analyzer issue due to the use of set literals, which require 2.1.0. Previously the app allowed lower versions.
=> Updates place_tracker to specify SDK >=2.1.0

.travis.yml, place_tracker/pubspec.lock, place_tracker/pubspec.yaml
Avoids double builds on PR + branch
=> Only run master on Travis

web/readme.md
Updated readme to include instructions to be able to build web sample apps locally.
=> added instructions to run web sample apps

place_tracker/ios/Podfile, platform_view_swift/ios/Podfile, veggieseasons/ios/Podfile, web/readme.md
Related to flutter/flutter#33041
=> Update to `flutter pub`

INDEX.md
=> Tweaking sample index

isolate_example/lib/main.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml, isolate_example/test/widget_test.dart, travis_script.sh
Three blank canvases for my 3 pages
=> Added 3 tabbed pages with welcome messages

isolate_example/lib/main.dart, isolate_example/lib/page_one.dart, isolate_example/lib/page_two.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml
This includes the two buttons with the compute method and the computation.
=> The rest of page one

isolate_example/lib/page_two.dart
A second page that runs computation on a second isolate that the user can control
=> Secondpage

jsonexample/analysis_options.yaml, jsonexample/lib/built_value/built_complex_object.dart, jsonexample/lib/built_value/built_simple_object.dart, jsonexample/lib/dart_convert/converted_complex_object.dart, jsonexample/lib/dart_convert/converted_simple_object.dart, jsonexample/lib/tab_pages.dart, jsonexample/lib/widgets.dart, jsonexample/pubspec.lock, jsonexample/pubspec.yaml, jsonexample/test/simple_object_unit_test.dart, jsonexample/test/widget_tests_test.dart
PTAL @RedBrogdon, looking at the deltas in this sample, we may want to back out the `strong-mode` requirements.
=> Add analysis_options, format and fix up

chrome-os-best-practices/analysis_options.yaml, chrome-os-best-practices/lib/main.dart, chrome-os-best-practices/pubspec.lock, chrome-os-best-practices/pubspec.yaml, chrome-os-best-practices/test/widget_test.dart, flutter_maps_firestore/pubspec.lock, isolate_example/pubspec.lock, jsonexample/pubspec.lock
First of the split off PRs, this time with all of the new lint rules
=> Add analysis_options, re-format, add commas.

isolate_example/lib/page_two.dart
Fixed major issue with page two isolate running in the background.
=> Page two bug fix

isolate_example/README.md
=> Updated README.md file

isolate_example/lib/page_three.dart, platform_view_swift/ios/Runner.xcodeproj/project.pbxproj
New feature added button for sending numbers with TransferableTypeData!
=> TransferableTypeData added

animations/lib/main.dart, animations/lib/src/misc/card_swipe.dart, animations/lib/src/misc/carousel.dart, animations/lib/src/misc/expand_card.dart, animations/lib/src/misc/focus_image.dart, animations/lib/src/misc/repeating_animation.dart
This adds @bratay's samples. These have already been reviewed but if there's anything that can be improved feel free to call it out.
=> add carousel, card_swipe, and focus_image samples

.travis.yml
=> use fonts-noto package

animations/lib/main.dart, animations/lib/src/basics/02_page_route_builder.dart, animations/lib/src/basics/05_custom_tween.dart, animations/lib/src/misc/physics_card_drag.dart
This adds the sample produced for the [Animate a widget using a physics simulation](https://flutter.dev/docs/cookbook/animation/physics-simulation) cookbook article.
=> Add scroll physics demo

experimental/README.md
Quick poll: is it better to call this folder `experimental` or something like `master_channel`?
=> Adding readme

animations/README.md
I forgot to add some descriptions to match the other samples in this project
=> update animations README

experimental/add_to_app/SimpleIOSExample/SimpleIOSExample.xcodeproj/project.pbxproj
See https://github.com/flutter/flutter/issues/39359.
=> Remove bitcode=NO from add-to-app flows

animations/lib/src/basics/07_tween_sequence.dart
=> call super.dispose() in sample

MAINTENANCE.md, isolate_example/.gitignore, isolate_example/.metadata, isolate_example/android/app/src/main/kotlin/dev/flutter/isolate_example/MainActivity.kt, isolate_example/ios/Runner/AppDelegate.swift, isolate_example/ios/Runner/Runner-Bridging-Header.h, isolate_example/lib/main.dart, isolate_example/lib/page_one.dart, isolate_example/lib/page_three.dart, isolate_example/lib/page_two.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml
Tidies the code a bit, refreshes the underlying project structure for 1.9, etc.
=> Quarterly maintenance on isolate_example

experimental/add_to_app/android_using_plugin/app/build.gradle, experimental/add_to_app/android_using_plugin/app/src/main/java/dev/flutter/example/androidusingplugin/MainActivity.kt, experimental/add_to_app/android_using_plugin/app/src/main/java/dev/flutter/example/androidusingplugin/MyApplication.kt, experimental/add_to_app/android_using_plugin/app/src/main/res/layout/activity_main.xml
Added some syntactic sugar for kotlin like lateinits and kotlin extension view references etc. I was just testing one thing in this project combo so I did some driveby but we should probably do this to all the kotlin code.
=> Some kotlin cosmetic tweaks

animations/lib/src/misc/physics_card_drag.dart
Updated spring animation sample to include some improvements based on code from @matthew-carroll
=> Updated spring animation example

experimental/add_to_app/android_using_plugin/app/src/main/java/dev/flutter/example/androidusingplugin/MyApplication.kt
Fix import from `dev.flutter.plugins.GeneratedPluginRegistrant` to `io.flutter.plugins.GeneratedPluginRegistrant` so that the code can be compiled.
=> Fix import

web/readme.md
=> add deployment documentation to web/ directory

MAINTENANCE.md, isolate_example/lib/data_transfer_page.dart, isolate_example/lib/infinite_process_page.dart, isolate_example/lib/main.dart, isolate_example/lib/performance_page.dart, isolate_example/pubspec.lock
- use slightly more meaningful names
- rename files
- misc small readability changes
=> isolate sample maintenance

gallery/README.md
Update links to adaptive.dart and splash.dart as relative links
=> Fix broken links in gallery sample readme.

experimental/README.md, experimental/add_to_app/README.md
@xster: go ahead and merge/modify this as you see fit.
=> Adding redirect README for add_to_app

experimental/desktop_photo_search/README.md
It looks like typo.
Thanks for the good examples.
=> README:fix typo

gallery/gallery/Makefile
- Remove deploy script as it's no longer used.
- Update the root folder in the Makefile, so that we can run the l10n script.
- Ran the formatter over the localization messages.
=> Modify Makefile in flutter/samples, so that we can run the l10n script

gallery/gallery/android/app/build.gradle, gallery/gallery/android/app/src/debug/AndroidManifest.xml, gallery/gallery/android/app/src/main/AndroidManifest.xml, gallery/gallery/android/app/src/main/kotlin/io/flutter/demo/gallery/MainActivity.kt, gallery/gallery/pubspec.yaml
There was an issue when releasing an APK file onto the app store. The APK file would break on launch. This PR fixed that problem.
=> Fix apk release issue for new Flutter Gallery

gallery/gallery/lib/studies/shrine/app.dart, gallery/gallery/lib/studies/shrine/login.dart, gallery/gallery/lib/studies/shrine/shopping_cart.dart, gallery/gallery/lib/studies/shrine/theme.dart
Add details for the Shrine study in the Gallery app:
Use correct letter spacing from the spec.
Closes part of
https://github.com/material-components/material-components-flutter-gallery/issues/141
(item 3)
* Old cart
* New cart
* Old login
* New login
=> Gallery — Shrine: Update Letter Spacing

gallery/gallery/lib/pages/settings.dart
Closes https://github.com/material-components/material-components-flutter-gallery/issues/507
=> [Gallery] Fix padding of bottom buttons on home page

CONTRIBUTING.md
* Updates the contributor's guide to explicitly list the conventions we expect each project to follow.
* Adds guidelines for which reviewers to add to a PR.
=> Updating CONTRIBUTING.md with repo conventions and review guide.

gallery/gallery/lib/pages/backdrop.dart
Closes https://github.com/material-components/material-components-flutter-gallery/issues/502
=> [Gallery] Ensure the ink is clipped on the settings button

gallery/gallery/lib/data/demos.dart
* Factor `GalleryLocalizations.of(context)` into a variable
* Factor the documentation base url into a variable
=> [Gallery] Refactor list of demos to use common variables

gallery/gallery/ios/Podfile.lock, gallery/gallery/lib/pages/about.dart, gallery/gallery/pubspec.lock, gallery/gallery/pubspec.yaml
Closes https://github.com/material-components/material-components-flutter-gallery/issues/529
=> [Gallery] Add version number to About dialog

gallery/gallery/lib/l10n/gallery_localizations.dart, gallery/gallery/lib/l10n/intl_en_US.arb, gallery/gallery/lib/l10n/intl_en_US.xml, gallery/gallery/lib/l10n/messages_en_US.dart, gallery/gallery/pubspec.lock
Closes https://github.com/material-components/material-components-flutter-gallery/issues/219
=> [Gallery] Update capitalization of cupertino demo titles to be consistent with Material

gallery/gallery/lib/studies/shrine/login.dart, gallery/gallery/macos/Podfile.lock
Closes https://github.com/material-components/material-components-flutter-gallery/issues/441
=> [Gallery] Prevent shrine login screen from allowing overscroll

gallery/gallery/lib/l10n/gallery_localizations.dart, gallery/gallery/lib/l10n/intl_en_US.arb, gallery/gallery/lib/l10n/intl_en_US.xml, gallery/gallery/lib/l10n/messages_en_US.dart, gallery/gallery/lib/studies/crane/model/formatters.dart, gallery/gallery/pubspec.lock, gallery/gallery/pubspec.yaml
Changes
=====
- Localize durations for Crane.
- Correctly formatted placeholders in intl_en_US.arb
- Ran the l10n script with latest Flutter version which updates it a bit.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/272
Screenshots
======
*Before*
*After*
=> [Gallery] Localize durations for Crane

gallery/gallery/lib/l10n/gallery_localizations.dart, gallery/gallery/lib/l10n/intl_en_US.arb, gallery/gallery/lib/l10n/intl_en_US.xml, gallery/gallery/lib/l10n/messages_en_US.dart
Also regenerate strings
Closes https://github.com/material-components/material-components-flutter-gallery/issues/410
=> Rename REFERENCE STYLES & MEDIA category to STYLES & OTHER

gallery/gallery/lib/main.dart, gallery/gallery/pubspec.lock, gallery/gallery/pubspec.yaml
Also:
Upgrade packages to latest allowable version
Specify ^ for packages missing it
=> [Gallery] Disallow GoogleFonts http loading

gallery/pubspec.yaml
=> [Gallery] Bump version to 2.3

provider_shopper/lib/main.dart, provider_shopper/lib/screens/login.dart, provider_shopper/test/widget_test.dart
Fixed #270 
I recreated the login page using the gif present at https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple as a reference.
Final Result 👇
=> Added missing login page

veggieseasons/lib/screens/list.dart
=> Veggieseasons - Fix feed scroll behind status bar

veggieseasons/lib/screens/details.dart
Fixed: #280 
Changes: Added _buildHelper in ListView in details.dart file. Also increased image size
Screenshots
=> addded overscroll in header section

add_to_app/android_using_prebuilt_module/app/build.gradle
Match URL in tool: https://github.com/flutter/flutter/pull/52042
=> Update Maven URL to https

experimental/README.md
=> Removing index from experimental README

platform_design/lib/profile_tab.dart
Fixes #363 
Polished LogOut dialog in the Adaptive Music App.
=> [platform_design] fix: Polished LogOut dialog

animations/README.md, animations/lib/main.dart, animations/lib/src/misc/hero_animation.dart
new animation sample: Hero Animation Demo
Additional Context:
[Hero Class](https://api.flutter.dev/flutter/widgets/Hero-class.html)
=> [animations] new animation sample: Hero Animation Demo

veggieseasons/lib/main.dart, veggieseasons/lib/screens/details.dart, veggieseasons/lib/screens/favorites.dart, veggieseasons/lib/screens/list.dart, veggieseasons/lib/screens/search.dart, veggieseasons/lib/screens/settings.dart, veggieseasons/lib/styles.dart, veggieseasons/lib/widgets/search_bar.dart, veggieseasons/lib/widgets/settings_group.dart, veggieseasons/lib/widgets/settings_item.dart, veggieseasons/lib/widgets/trivia.dart, veggieseasons/lib/widgets/veggie_headline.dart
Fixes problems in #322
I've changed the declared const Styles to a method which were causing the issues.
Please take a look @RedBrogdon @johnpryan.
Screencast:
I've made sure that nothing breaks in the light mode as well
=> [VeggieSeasons] Fix dark mode problems

web/samples_index/lib/src/samples.yaml
=> [visual sample index] Fix broken link Timeflow sourcecode

.travis.yml, add_to_app/flutter_module/lib/main.dart, add_to_app/flutter_module/pubspec.lock, add_to_app/flutter_module_using_plugin/lib/main.dart, isolate_example/lib/infinite_process_page.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml, jsonexample/lib/tab_pages.dart, jsonexample/lib/widgets.dart, platform_design/lib/widgets.dart, platform_view_swift/lib/main.dart, provider_shopper/lib/screens/cart.dart, tool/travis_flutter_script.sh
Updates the samples in these folders:
* jsonexample
* add_to_app
* platform_design
* isolate_example
* veggieseasons
For the current beta release. Mostly font changes and pubspec upgrades. Also includes a change to the travis config that should cause the beta branch to be tested.
=> Updates additional samples for beta release

animations/README.md, animations/lib/main.dart, animations/lib/src/misc/curved_animation.dart
#382 
The sample includes a rotating flutter logo which generates random curves for forward and reverse rotations every time the animate button is pressed to demonstrate the use of different curves with CurvedAnimation.
=> Added CurvedAnimation Sample

animations/pubspec.lock, animations/test/misc/expand_card_test.dart
Adds widget test for `ExpandCardDemo`.
Related Issue #399
=> [animations] adds widget test for expand card 

provider_shopper/lib/models/catalog.dart, provider_shopper/test/cart_widget_test.dart, provider_shopper/test/catalog_widget_test.dart, provider_shopper/test/login_widget_test.dart
Fixes #387 
Added widget tests for login, catalog and cart screens.
=> [provider_shopper] Added widget tests for login, catalog and cart screens

gallery/README.md, web/samples_index/lib/src/samples.yaml
https://github.com/flutter/gallery/issues/139
=> Update Flutter Gallery link

veggieseasons/.gitignore, veggieseasons/ios/Podfile.lock, veggieseasons/ios/Runner.xcodeproj/project.pbxproj, veggieseasons/pubspec.lock, veggieseasons/pubspec.yaml
Dependency update removes a deprecation warning during launch and during first run flutter was upgrading the xcode project to the latest version.
=> [Veggie Seasons] Update dependencies on xcode project

animations/test/misc/card_swipe_test.dart
This PR adds widget tests for Card Swipe in the Animations app.
@domesticmouse @RedBrogdon reviews, please.
=> [animations] Add widget tests for card_swipe

CONTRIBUTING.md
=> fixes broken link to CI script

CONTRIBUTING.md
fixes: https://github.com/flutter/samples/issues/449
=> Linking to a analysis_options.yaml that is present

animations/test/misc/carousel_test.dart
Adds test for `CarouselDemo` in animations.
#399
I'm looking forward to what other tests we can include for the `CarouselDemo`.
=> [animations] adds test for CarouselDemo

.travis.yml
Setting up a long lived branch for development of a testing sample.
=> Adding testing_sample as a tested branch

flutter_maps_firestore/ios/Runner/Info.plist
=> fix ios install

testing_app/README.md, testing_app/test/models/favorites_test.dart
Added a unit test for testing the provider.
Does this qualify as a State Management Test?
/cc: @domesticmouse @RedBrogdon
=> [testing_app] Add provider tests

experimental/desktop_photo_search/linux/flutter/generated_plugin_registrant.cc, experimental/desktop_photo_search/linux/flutter/generated_plugins.cmake
=> Update linux compilation generated files

testing_app/README.md, testing_app/test_driver/state_mgmt.dart, testing_app/test_driver/state_mgmt_test.dart
State Management Tests using Flutter Driver added.
/cc: @domesticmouse @RedBrogdon
=> [testing_app] Add State Management Tests

testing_app/README.md, testing_app/test_driver/perf.dart, testing_app/test_driver/perf_test.dart
@domesticmouse reviews, please.
=> [testing_app] Add Performance tests

experimental/web_dashboard/lib/main.dart, experimental/web_dashboard/lib/main_firebase.dart, experimental/web_dashboard/lib/src/app.dart, experimental/web_dashboard/tool/grind.dart
Most users will want to run this sample using the mock APIs, since firebase needs to be set up to use the firebase versions.
=> Default to mock version in web_dashboard

testing_app/test_driver/state_mgmt_test.dart
=> [testing_app] Fix typos in the comments

place_tracker/README.md
update caveats section, add iOS instructions
=> Update place_tracker README

testing_app/test/favorites_test.dart, testing_app/test/models/favorites_test.dart
/cc @domesticmouse @RedBrogdon
=> [testing_app] Remove usage of random numbers in the tests

animations/lib/src/misc/animated_list.dart
fixes #540 
#541 I was unable to get #541 working so I created a new pr.
@AyushBherwani1998 @abd99 @RedBrogdon
=> [Animations] Add remove-button

animations/test/misc/animated_positioned_test.dart
Adds widget test for `AnimatedPositioned`
In regard to issue #399
=> [animations] adds test for AnimatedPositioned

experimental/federated_plugin/federated_plugin/example/ios/Flutter/Debug.xcconfig, experimental/federated_plugin/federated_plugin/example/ios/Flutter/Release.xcconfig, experimental/federated_plugin/federated_plugin/example/ios/Podfile, experimental/federated_plugin/federated_plugin/example/ios/Podfile.lock, experimental/federated_plugin/federated_plugin/example/ios/Runner.xcodeproj/project.pbxproj, experimental/federated_plugin/federated_plugin/example/ios/Runner.xcworkspace/contents.xcworkspacedata, experimental/federated_plugin/federated_plugin/example/pubspec.lock, experimental/federated_plugin/federated_plugin/ios/Classes/SwiftFederatedPlugin.swift, experimental/federated_plugin/federated_plugin/pubspec.lock, experimental/federated_plugin/federated_plugin/pubspec.yaml
Adds iOS implementation for federated_plugin
cc:// @RedBrogdon @domesticmouse  I don't have Apple Developer account to test it on my iPhone, and on simulator it throws exception. I read that you can get battery level of simulator on reddit. It would be great if you can check it when ever you get time.
=> [federated_plugin] add iOS implementation

testing_app/lib/screens/favorites.dart, testing_app/test/favorites_test.dart, testing_app/test/models/favorites_test.dart
Added a simple placeholder message for the favorites list page.
Related Issue #578
=> [testing_app] added basic placeholder for favorites list

animations/lib/src/basics/05_animated_builder.dart
Related Issue #568 and Pull Request #569 
Since @Raj-Dave368 is not responding to the mentioned PR for over a month. I thought to solve the pending issue.
I have increased the button size by some amount, using height and weight which makes the change appear clearly (refer to the attached image).
@RedBrogdon, Kindly review the changes.
=> [Animations] Button size increased

web/samples_index/lib/src/carousel.dart, web/samples_index/lib/src/templates.dart, web/samples_index/web/description.dart, web/samples_index/web/styles.scss
Fixes #393 
I've implemented an animated carousel using dart and scss. Font awesome icons are used for the left and right arrows. Hope this would solve the issue. :)
A preview is added below for reference,
=> [samples_index] Implement carousel

experimental/desktop_photo_search/macos/Runner.xcodeproj/project.pbxproj, experimental/desktop_photo_search/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, experimental/desktop_photo_search/macos/Runner/Base.lproj/MainMenu.xib, experimental/desktop_photo_search/pubspec.lock
Hide the titlebar & update deps
=> Update macOS desktop sample

navigation_and_routing/README.md
Added local links for the files inside the project to take the reader directly to code.
=> [navigation_and_routing] updated README 

platform_channels/README.md, platform_channels/ios/Runner/AppDelegate.swift, platform_channels/lib/main.dart, platform_channels/lib/src/pet_list_screen.dart
Adds BasicMessageChannel Demo implementation for iOS. With this PR, the platform_channels sample is completed 🎉
=> [platform_channels] adds implementation of BasicMessageChannel for iOS

tool/flutter_ci_script.sh
I'd like to know if the generated_plugin_registrant issue is still around.
=> Added echo to test script

navigation_and_routing/README.md
=> format navigation_and_routing README

animations/test/misc/hero_animation_test.dart
Added widget test for `HeroAnimation`
This is with regard to issue #399
=> [animations] added test for HeroAnimation

README.md
Replaced flutter.io with flutter.dev in main README.md
=> Updated flutter website URL in README

experimental/web_dashboard/lib/src/pages/entries.dart
=> Fix web_dashboard analysis warnings on beta channel

animations/lib/src/basics/06_custom_tween.dart
=> bug fix in CutomTweenDemo

animations/test/misc/animated_list_test.dart
Added test for `AnimatedList`
This is with regard to issue #399
=> [animations]: added test for AnimatedList

form_app/lib/src/autofill.dart
Though this is sample to show autofill in forms, Its good to have keyboard type with field .
=> Added keyboard InputType in autofill form

platform_channels/lib/src/method_channel_demo.dart, platform_channels/lib/src/pet_list_screen.dart, platform_channels/pubspec.lock
fixed related issue #656 for the upcoming release.
cc: @domesticmouse,@RedBrogdon, @AyushBherwani1998
=> Updated platform_channels for upcoming release

experimental/federated_plugin/federated_plugin/example/lib/main.dart, experimental/federated_plugin/federated_plugin/example/pubspec.lock, experimental/federated_plugin/federated_plugin/pubspec.lock
fixed related issue #659  for the upcoming release.
cc: @domesticmouse,@RedBrogdon, @AyushBherwani1998
=> Updated experimental/federated_plugin/federated_plugin for upcoming release

isolate_example/lib/performance_page.dart, isolate_example/pubspec.lock
**fixed related issue #653  for the upcoming release.**
cc: @domesticmouse,@RedBrogdon
=> Updated  isolate_example for upcoming release

provider_shopper/lib/screens/cart.dart, provider_shopper/pubspec.lock
fixed related issue #657  for the upcoming release.
cc: @domesticmouse,@RedBrogdon
=> Updated provider_shopper for upcoming release

place_tracker/lib/place_map.dart, place_tracker/pubspec.lock
fixed related issue  #655 for the upcoming release.
cc: @domesticmouse,@RedBrogdon
=> Updated place_tracker for upcoming release

.github/workflows/beta.yml, .github/workflows/main.yml, README.md
This creates a second workflow that runs on the beta branch. There are a number of outstanding PRs that should be landed there, making this a needed first step.
FWIW, it's probably possibly to do some YAML-fu and get both branches into a single workflow, but I like the idea of having two completely separate ones.
=> Adding new workflow for beta.

experimental/federated_plugin/federated_plugin/pubspec.yaml, experimental/federated_plugin/federated_plugin_platform_interface/pubspec.yaml, experimental/federated_plugin/federated_plugin_web/pubspec.yaml, experimental/federated_plugin/federated_plugin_windows/pubspec.yaml
Align example pubspecs with new templates, removing unused upper constraint
https://github.com/flutter/flutter/pull/68437
=> Update example pubspecs to match templates

CONTRIBUTING.md
This PR simply updates the year in the [File Header](https://github.com/flutter/samples/blob/master/CONTRIBUTING.md#file-header) section.
=> Update file header date in CONTRIBUTING.md

form_app/lib/src/autofill.dart, form_app/lib/src/sign_in_http.dart, form_app/lib/src/validation.dart
Added FocusNodes to improve user experience in form_app.
=> Added Focusnodes in form sample

jsonexample/ios/Runner.xcodeproj/project.pbxproj, jsonexample/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, jsonexample/lib/built_value/built_complex_object.dart, jsonexample/lib/built_value/built_complex_object.g.dart, jsonexample/lib/built_value/built_simple_object.dart, jsonexample/lib/built_value/built_simple_object.g.dart, jsonexample/lib/dart_convert/converted_complex_object.dart, jsonexample/lib/dart_convert/converted_simple_object.dart, jsonexample/lib/json_serializable/serializable_complex_object.dart, jsonexample/lib/json_serializable/serializable_complex_object.g.dart, jsonexample/lib/json_serializable/serializable_simple_object.dart, jsonexample/lib/json_serializable/serializable_simple_object.g.dart, jsonexample/lib/main.dart, jsonexample/lib/tab_pages.dart, jsonexample/lib/utils.dart, jsonexample/lib/widgets.dart, jsonexample/pubspec.lock, jsonexample/pubspec.yaml, jsonexample/test/complex_object_unit_test.dart
Updates dependencies to null-safe versions, opts-in the code, and makes the necessary changes to syntax.
=> [beta branch] Migrated jsonexample

animations/test/misc/focus_image_test.dart
Added widget test for `FocusImage`.
ref: #399
=> [animations] added test for focus image

provider_counter/pubspec.lock, provider_counter/pubspec.yaml
fixes: #720 
* Updated dependencies.
* Migrated using dart migrate.
/cc @filiph @domesticmouse @RedBrogdon
=> [provider_counter] migrate to null safety

platform_design/lib/main.dart, platform_design/lib/news_tab.dart, platform_design/lib/profile_tab.dart, platform_design/lib/song_detail_tab.dart, platform_design/lib/songs_tab.dart, platform_design/lib/utils.dart, platform_design/lib/widgets.dart, platform_design/pubspec.lock, platform_design/pubspec.yaml
* Upgraded dependencies
* Migrated sample to null-safety
closes #726
/cc @filiph @domesticmouse @RedBrogdon
=> Migrate platform_design to null safety

experimental/federated_plugin/federated_plugin_web/README.md, experimental/federated_plugin/federated_plugin_web/pubspec.lock, experimental/federated_plugin/federated_plugin_web/pubspec.yaml, experimental/federated_plugin/federated_plugin_web/test_driver/federated_plugin_web_integration.dart, experimental/federated_plugin/federated_plugin_web/test_driver/federated_plugin_web_integration_test.dart
Migrates e2e tests for browser to integration tests.
Fixes #743
=> [federated_pluign] migrate e2e test to integration test

provider_shopper/lib/main.dart, provider_shopper/lib/models/cart.dart, provider_shopper/lib/screens/cart.dart, provider_shopper/lib/screens/catalog.dart, provider_shopper/pubspec.lock, provider_shopper/pubspec.yaml, provider_shopper/test/cart_widget_test.dart, provider_shopper/test/catalog_widget_test.dart, provider_shopper/test/login_widget_test.dart
fixes: #729 
* updated dependencies.
* migrated using "dart migrate".
Have a look @filiph @RedBrogdon @domesticmouse
=> [provider_shopper] migrate to null safe

tool/ios_ci_script.sh
This should not be merged until the next stable release.
=> Restores `add_to_app/multiple_flutters/multiple_flutters_ios` to the iOS CI list

testing_app/integration_test/app_test.dart, testing_app/integration_test/driver.dart, testing_app/integration_test/perf_test.dart, testing_app/pubspec.lock
After the release of Flutter 2, there were some integration tests that were failing in the sample.
This PR fixes those issues.
Please note that this sample does not use null-safety yet.
/cc @johnpryan
=> [testing_app] Fix failing integration tests

tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_dev.sh, tool/flutter_ci_script_shared.sh, tool/flutter_ci_script_stable.sh
fixes https://github.com/flutter/samples/issues/759
=> extracted copy and pasted function across module ci scripts

add_to_app/android_view/android_view/build.gradle, add_to_app/android_view/android_view/gradle/wrapper/gradle-wrapper.properties, add_to_app/android_view/android_view/settings.gradle, add_to_app/books/android_books/build.gradle, add_to_app/books/android_books/gradle/wrapper/gradle-wrapper.properties, add_to_app/books/android_books/settings.gradle
Update AGP to prevent the class of issues like https://github.com/flutter/samples/issues/737. 
Background context https://github.com/flutter/flutter/issues/53657#issuecomment-795808016
=> Update host Android projects away from problematic AGP versions

add_to_app/android_view/flutter_module_using_plugin/lib/main.dart
Fixes https://github.com/flutter/flutter/issues/81350
=> Add an entry point annotation to the Dart function invoked by the android_view sample

form_app/pubspec.lock, infinite_list/analysis_options.yaml, infinite_list/android/app/build.gradle, infinite_list/android/app/src/debug/AndroidManifest.xml, infinite_list/android/app/src/main/AndroidManifest.xml, infinite_list/android/app/src/main/kotlin/dev/flutter/infinite_list/MainActivity.kt, infinite_list/android/app/src/main/res/drawable-v21/launch_background.xml, infinite_list/android/app/src/main/res/values-night/styles.xml, infinite_list/android/app/src/profile/AndroidManifest.xml, infinite_list/android/build.gradle, infinite_list/android/gradle.properties, infinite_list/android/gradle/wrapper/gradle-wrapper.properties, infinite_list/ios/.gitignore, infinite_list/ios/Flutter/AppFrameworkInfo.plist, infinite_list/ios/Runner.xcodeproj/project.pbxproj, infinite_list/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, infinite_list/ios/Runner/Info.plist, infinite_list/lib/main.dart, infinite_list/pubspec.yaml, infinite_list/test/smoke_test.dart, infinite_list/web/index.html
=> `infinite_list`: Adjust lint rules and rebuild Android, iOS and Web runners

add_to_app/android_view/flutter_module_using_plugin/analysis_options.yaml, add_to_app/android_view/flutter_module_using_plugin/lib/cell.dart, add_to_app/android_view/flutter_module_using_plugin/lib/main.dart, add_to_app/android_view/flutter_module_using_plugin/pubspec.lock, add_to_app/android_view/flutter_module_using_plugin/pubspec.yaml, add_to_app/android_view/flutter_module_using_plugin/test/widget_test.dart
And another `flutter_lints` PR. I'm doing one per module, to try and limit the size of the PR.
=> Add `flutter_lints` to `add_to_app/android_view/flutter_module_using_plugin`

add_to_app/fullscreen/flutter_module/analysis_options.yaml, add_to_app/fullscreen/flutter_module/lib/main.dart, add_to_app/fullscreen/flutter_module/pubspec.lock, add_to_app/fullscreen/flutter_module/pubspec.yaml, add_to_app/fullscreen/flutter_module/test/widget_test.dart
I'm doing the samples one module at a time, to reduce the size of the PRs.
=> Add `flutter_lints` to `add_to_app/fullscreen/flutter_module`

add_to_app/multiple_flutters/multiple_flutters_module/analysis_options.yaml, add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart, add_to_app/multiple_flutters/multiple_flutters_module/pubspec.lock, add_to_app/multiple_flutters/multiple_flutters_module/pubspec.yaml
=> Add `flutter_lints` to `add_to_app/multiple_flutters/multiple_flutters_module`

tool/flutter_ci_script_shared.sh
Follow on from https://github.com/flutter/samples/pull/846#pullrequestreview-703270855
=> `flutter analyze` -> `dart analyze`

navigation_and_routing/README.md, navigation_and_routing/lib/main.dart, navigation_and_routing/lib/src/app.dart, navigation_and_routing/lib/src/auth.dart, navigation_and_routing/lib/src/data.dart, navigation_and_routing/lib/src/data/library.dart, navigation_and_routing/lib/src/routing.dart, navigation_and_routing/lib/src/routing/parsed_route.dart, navigation_and_routing/lib/src/routing/parser.dart, navigation_and_routing/lib/src/routing/route_state.dart, navigation_and_routing/lib/src/screens/book_details.dart, navigation_and_routing/lib/src/screens/books.dart, navigation_and_routing/lib/src/screens/navigator.dart, navigation_and_routing/lib/src/screens/settings.dart, navigation_and_routing/lib/src/screens/sign_in.dart, navigation_and_routing/lib/src/widgets/fade_transition_page.dart, navigation_and_routing/test/library_test.dart
This adds a README and addresses code review comments that were missed in the [first PR](https://github.com/flutter/samples/pull/832).
@chunhtai the only change I didn't make was to make the `BookstoreAuth.signedIn` getter async. Firebase for example has a [synchronous `user` getter](https://firebase.google.com/docs/auth/web/manage-users) to check if a user is signed in.
=> Update Navigation and Routing sample

navigation_and_routing/lib/src/routing/parser.dart, navigation_and_routing/lib/src/routing/route_state.dart, navigation_and_routing/lib/src/screens/author_details.dart, navigation_and_routing/lib/src/screens/authors.dart, navigation_and_routing/lib/src/screens/book_details.dart, navigation_and_routing/lib/src/screens/navigator.dart, navigation_and_routing/lib/src/screens/scaffold_body.dart, navigation_and_routing/lib/src/screens/settings.dart, navigation_and_routing/old_snippets/router_advanced/transition_delegate.dart, navigation_and_routing/pubspec.yaml
single quotes everywhere
fix comment references
=> General cleanup: consistent quoting, sort dependencies,

.github/workflows/beta.yml, .github/workflows/gh-pages.yml, .github/workflows/main.yml, .github/workflows/verify-web-demos.yml
Adds hardcoded commits for the GitHub actions we're using for CI/CD.
See this issue for the (security-related) rationale: https://github.com/flutter/flutter/issues/87504
=> Pinning versions to commits

navigation_and_routing/pubspec.lock, web/_tool/pubspec.lock, web/samples_index/lib/cookbook.dart, web/samples_index/lib/samples_index.dart, web/samples_index/lib/src/carousel.dart, web/samples_index/lib/src/data.dart, web/samples_index/lib/src/data.g.dart, web/samples_index/lib/src/samples.yaml, web/samples_index/lib/src/search.dart, web/samples_index/lib/src/templates.dart, web/samples_index/lib/src/util.dart, web/samples_index/pubspec.yaml, web/samples_index/test/samples_index_test.dart, web/samples_index/test/yaml/single.yaml, web/samples_index/tool/grind.dart, web/samples_index/web/description.dart, web/samples_index/web/main.dart
Fixes #848 
Here's a sample CI run on my fork: https://github.com/johnpryan/samples/runs/3223933935?check_suite_focus=true
=> Fix sample index deployment action

web/samples_index/lib/src/samples.yaml
Fixes https://github.com/flutter/samples/issues/865
=> Fix broken source code link

experimental/linting_tool/lib/app.dart, experimental/linting_tool/lib/model/profiles_store.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/repository/api_provider.dart, experimental/linting_tool/lib/repository/repository.dart, experimental/linting_tool/linux/flutter/generated_plugin_registrant.cc, experimental/linting_tool/linux/flutter/generated_plugins.cmake, experimental/linting_tool/macos/Flutter/GeneratedPluginRegistrant.swift, experimental/linting_tool/macos/Podfile.lock, experimental/linting_tool/macos/Runner/DebugProfile.entitlements, experimental/linting_tool/macos/Runner/Release.entitlements, experimental/linting_tool/pubspec.lock, experimental/linting_tool/pubspec.yaml, experimental/linting_tool/test/widget_test.dart, experimental/linting_tool/windows/flutter/generated_plugin_registrant.cc, experimental/linting_tool/windows/flutter/generated_plugins.cmake
=> [linting_tool] Implement exporting profiles

experimental/linting_tool/lib/model/profiles_store.dart
=> [linting_tool] Stop duplication of rules in the same profile

experimental/linting_tool/lib/model/rules_store.dart, experimental/linting_tool/lib/pages/default_lints_page.dart
=> [linting_tool] Implement default lints page

experimental/linting_tool/lib/model/editing_controller.dart, experimental/linting_tool/lib/model/profiles_store.dart, experimental/linting_tool/lib/pages/rules_page.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/widgets/saved_rule_tile.dart, experimental/linting_tool/linux/flutter/generated_plugin_registrant.cc, experimental/linting_tool/linux/flutter/generated_plugins.cmake, experimental/linting_tool/macos/Flutter/GeneratedPluginRegistrant.swift, experimental/linting_tool/macos/Podfile.lock, experimental/linting_tool/pubspec.lock, experimental/linting_tool/pubspec.yaml, experimental/linting_tool/windows/flutter/generated_plugin_registrant.cc, experimental/linting_tool/windows/flutter/generated_plugins.cmake
- Implemented editing functionality for profiles
- Added right-click context menu to remove a single rule from a profile
/cc @domesticmouse
=> [linting_tool] Implement editing profile

experimental/linting_tool/lib/pages/default_lints_page.dart, experimental/linting_tool/lib/pages/default_rules_page.dart
- Added new `DefaultRulesPage` to fix build
/cc @domesticmouse
=> [linting_tool] Fix build

experimental/linting_tool/README.md, experimental/linting_tool/lib/main.dart, experimental/linting_tool/lib/model/editing_controller.dart, experimental/linting_tool/lib/model/profiles_store.dart, experimental/linting_tool/lib/model/rules_store.dart, experimental/linting_tool/lib/pages/default_lints_page.dart, experimental/linting_tool/lib/pages/default_rules_page.dart, experimental/linting_tool/lib/pages/home_page.dart, experimental/linting_tool/lib/pages/rules_page.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/theme/app_theme.dart, experimental/linting_tool/lib/widgets/adaptive_nav.dart, experimental/linting_tool/lib/widgets/lint_expansion_tile.dart, experimental/linting_tool/linux/flutter/generated_plugin_registrant.cc, experimental/linting_tool/linux/flutter/generated_plugins.cmake, experimental/linting_tool/macos/Flutter/GeneratedPluginRegistrant.swift, experimental/linting_tool/macos/Podfile.lock, experimental/linting_tool/pubspec.lock, experimental/linting_tool/pubspec.yaml, experimental/linting_tool/windows/flutter/generated_plugin_registrant.cc, experimental/linting_tool/windows/flutter/generated_plugins.cmake, platform_channels/pubspec.lock
* Minimum window size set
* Improved padding for lists when for small window size
* Improved comments and code formatting
* Stopped 'existing' option from appearing while saving new rule if no profiles exist.
* Added text to about dialog
* Updated README
@domesticmouse
=> [linting_tool] Prepare for release

testing_app/README.md, testing_app/integration_test/perf_driver.dart
@johnpryan, should I do something similar for the codelab too?
=> [testing_app] Add separate driver file for performance tests

form_app/pubspec.lock
If you need help, consider asking for advice on the #hackers-new channel on [Discord].
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
=> Update `pubspec.lock` to be in line with `pubspec.yaml`

experimental/web_dashboard/lib/src/api/api.dart, experimental/web_dashboard/lib/src/api/firebase.dart, experimental/web_dashboard/lib/src/api/mock.dart, experimental/web_dashboard/lib/src/app.dart, experimental/web_dashboard/lib/src/auth/firebase.dart, experimental/web_dashboard/lib/src/auth/mock.dart, experimental/web_dashboard/lib/src/pages/dashboard.dart, experimental/web_dashboard/lib/src/pages/entries.dart, experimental/web_dashboard/lib/src/pages/home.dart, experimental/web_dashboard/lib/src/pages/sign_in.dart, experimental/web_dashboard/lib/src/utils/chart_utils.dart, experimental/web_dashboard/lib/src/widgets/categories_dropdown.dart, experimental/web_dashboard/lib/src/widgets/category_chart.dart, experimental/web_dashboard/lib/src/widgets/category_forms.dart, experimental/web_dashboard/lib/src/widgets/dialogs.dart, experimental/web_dashboard/lib/src/widgets/edit_entry.dart, experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart, experimental/web_dashboard/pubspec.lock, experimental/web_dashboard/pubspec.yaml, experimental/web_dashboard/test/mock_service_test.dart
This is currently using an unreleased version of charts_flutter due to https://github.com/google/charts/issues/678
=> Migrate web dashboard to null safety

.gitattributes
Automatically convert EOL to line feed to make Windows development of samples easier.
Inspiration from https://github.com/flutter/flutter/blob/master/.gitattributes
=> Add a `.gitattributes` file

navigation_and_routing/lib/src/routing/delegate.dart
=> Remove `ignore prefer_initializing_formals`

add_to_app/books/README.md, add_to_app/books/flutter_module_books/lib/api.dart, place_tracker/lib/stub_data.dart
This PR remove two places of unneeded `return`, which are not inside a loop.
Also, small typos were fixed.
=> Remove unneeded `return`

add_to_app/books/flutter_module_books/lib/api.dart, add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart, android_splash_screen/lib/main.dart, animations/lib/src/basics/08_fade_transition.dart, animations/lib/src/misc/animated_list.dart, animations/lib/src/misc/card_swipe.dart, experimental/desktop_photo_search/lib/main.dart, experimental/desktop_photo_search/lib/src/widgets/about_dialog.dart, experimental/desktop_photo_search/lib/src/widgets/photo_search_dialog.dart, experimental/web_dashboard/lib/src/widgets/dialogs.dart, experimental/web_dashboard/lib/src/widgets/edit_entry.dart, form_app/lib/src/autofill.dart, ios_app_clip/lib/main.dart, jsonexample/test/simple_object_unit_test.dart, place_tracker/lib/stub_data.dart, platform_channels/lib/src/add_pet_details.dart, provider_counter/lib/main.dart, testing_app/lib/screens/home.dart, veggieseasons/lib/screens/details.dart, veggieseasons/lib/screens/settings.dart, veggieseasons/lib/widgets/settings_item.dart, veggieseasons/lib/widgets/veggie_card.dart, web/charts/lib/axes/line_disjoint_axis.dart, web/charts/lib/axes/statically_provided_ticks.dart, web/charts/lib/drawer.dart, web/charts/lib/gallery_scaffold.dart, web/github_dataviz/lib/catmull.dart, web/github_dataviz/lib/layered_chart.dart, web/github_dataviz/lib/main.dart, web/particle_background/lib/main.dart
=> Remove unneeded types

experimental/web_dashboard/pubspec.lock, experimental/web_dashboard/pubspec.yaml, web/charts/pubspec.lock, web/charts/pubspec.yaml
Update to the latest release of `charts_flutter`
=> Update charts_flutter to 0.12.0

web/charts/lib/behaviors/slider.dart, web/github_dataviz/lib/constants.dart, web/github_dataviz/lib/layered_chart.dart
Fix up `web/github_dataviz` and `web/charts`.
The remaining failure is in `slide_puzzle` and I have https://github.com/kevmoo/slide_puzzle/pull/17 out as a partial fix.
/cc @kevmoo 
=> Resolving CI failures in `web`

navigation_and_routing/lib/src/app.dart, navigation_and_routing/lib/src/data/author.dart, navigation_and_routing/lib/src/screens/navigator.dart, navigation_and_routing/lib/src/screens/settings.dart
=> Remove unnecessary types

experimental/linting_tool/lib/theme/app_theme.dart, experimental/linting_tool/pubspec.lock, experimental/linting_tool/pubspec.yaml
=> `linting_tool`: Fix warnings and update dependencies

testing_app/README.md
Added the new(now almost old) command to run integration tests to the README.
@domesticmouse 
=> `testing_app`: Update README.md

add_to_app/android_view/android_view/app/build.gradle, add_to_app/android_view/android_view/build.gradle, add_to_app/books/android_books/app/build.gradle, add_to_app/books/android_books/build.gradle, add_to_app/fullscreen/android_fullscreen/app/build.gradle, add_to_app/fullscreen/android_fullscreen/build.gradle, add_to_app/fullscreen/flutter_module/pubspec.lock, add_to_app/multiple_flutters/multiple_flutters_android/app/build.gradle, add_to_app/multiple_flutters/multiple_flutters_android/build.gradle, add_to_app/multiple_flutters/multiple_flutters_module/pubspec.lock, add_to_app/plugin/android_using_plugin/app/build.gradle, add_to_app/plugin/android_using_plugin/build.gradle, add_to_app/plugin/flutter_module_using_plugin/pubspec.lock, add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle, add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle, add_to_app/prebuilt_module/flutter_module/pubspec.lock
Just trying to get the tests right in the beta branch. A general pubspec update is to follow.
=> Correcting Android build failures.

jsonexample/android/.gitignore, jsonexample/android/app/build.gradle, jsonexample/android/app/src/main/AndroidManifest.xml, jsonexample/android/app/src/main/res/values-night/styles.xml, jsonexample/android/app/src/main/res/values/styles.xml, jsonexample/android/build.gradle
Like in the other PRs, working to clean up and upgrade the Android files for the jsonexample project. In this case, some dependencies were outdated and the project was not running anymore on a fresh setup.
This PR fixes it by recreating the android folder using Flutter 2.10.1
=> Update Android files in jsonexample

isolate_example/android/.gitignore, isolate_example/android/app/build.gradle, isolate_example/android/app/src/main/AndroidManifest.xml, isolate_example/android/app/src/main/res/values-night/styles.xml, isolate_example/android/app/src/main/res/values/styles.xml, isolate_example/android/build.gradle
Like in the other PRs, working to clean up and upgrade the Android files for the isolate_example project. In this case, some dependencies were outdated and the project was not running anymore on a fresh setup.
This PR fixes it by recreating the android folder using Flutter 2.10.1
=> Update Android files in isolate_example

form_app/android/.gitignore, form_app/android/app/build.gradle, form_app/android/app/src/main/AndroidManifest.xml, form_app/android/app/src/main/res/values-night/styles.xml, form_app/android/app/src/main/res/values/styles.xml, form_app/android/build.gradle, form_app/pubspec.lock
Like in the other PRs, working to clean up and upgrade the Android files for the form_app project.
This PR fixes it by recreating the android folder using Flutter 2.10.1
=> Update Android files in form_app

animations/android/.gitignore, animations/android/app/build.gradle, animations/android/app/src/main/AndroidManifest.xml, animations/android/app/src/main/kotlin/dev/flutter/animations/MainActivity.kt, animations/android/app/src/main/res/drawable-v21/launch_background.xml, animations/android/app/src/main/res/values-night/styles.xml, animations/android/build.gradle, animations/android/gradle.properties, animations/android/gradle/wrapper/gradle-wrapper.properties, animations/android/settings.gradle
Work to clean up and upgrade the Android files for the animations project.
Before, it was not possible to run the project on Android due to using the v1 embedding.
This PR fixes this by recreating the android folder using Flutter 2.10.1
=> Update Android files in animations

infinite_list/android/.gitignore, infinite_list/android/app/build.gradle, infinite_list/android/app/src/main/AndroidManifest.xml, infinite_list/android/app/src/main/res/values-night/styles.xml, infinite_list/android/app/src/main/res/values/styles.xml, infinite_list/android/build.gradle
Work to clean up and upgrade the Android files for the infinite_list project.
It was not possible to run the project previously because some dependency versions were too old.
This PR fixes this by recreating the android folder using Flutter 2.10
=> Update Android files in infinite_list

platform_channels/android/.gitignore, platform_channels/android/app/build.gradle, platform_channels/android/app/src/main/AndroidManifest.xml, platform_channels/android/app/src/main/res/drawable-v21/launch_background.xml, platform_channels/android/app/src/main/res/values-night/styles.xml, platform_channels/android/build.gradle, platform_channels/android/gradle.properties, platform_channels/android/gradle/wrapper/gradle-wrapper.properties
Updated Android files for the platform_channel sample.
- The application ID was not consistent with the rest of the app, so I changed it to `dev.flutter.platform_channels`.
- The original Kotlin code and assets are maintained.
=> Update platform_channels Android files

place_tracker/android/.gitignore, place_tracker/android/app/build.gradle, place_tracker/android/app/src/main/AndroidManifest.xml, place_tracker/android/app/src/main/res/values-night/styles.xml, place_tracker/android/app/src/main/res/values/styles.xml, place_tracker/android/build.gradle
Updated place_tracker Android files.
- The min SDK needs to be 20 as required by the Google Maps package.
- The metadata tags for the Maps API has been kept in the AndroidManifest.xml
=> Update place_tracker Android files

null_safety/null_safe_app/android/.gitignore, null_safety/null_safe_app/android/app/build.gradle, null_safety/null_safe_app/android/app/src/main/AndroidManifest.xml, null_safety/null_safe_app/android/app/src/main/res/drawable-v21/launch_background.xml, null_safety/null_safe_app/android/app/src/main/res/values-night/styles.xml, null_safety/null_safe_app/android/app/src/main/res/values/styles.xml, null_safety/null_safe_app/android/build.gradle, null_safety/null_safe_app/android/gradle.properties, null_safety/null_safe_app/android/gradle/wrapper/gradle-wrapper.properties, null_safety/null_safe_app/android/null_safe_app_android.iml, null_safety/null_unsafe_app/android/.gitignore, null_safety/null_unsafe_app/android/app/build.gradle, null_safety/null_unsafe_app/android/app/src/main/AndroidManifest.xml, null_safety/null_unsafe_app/android/app/src/main/res/drawable-v21/launch_background.xml, null_safety/null_unsafe_app/android/app/src/main/res/values-night/styles.xml, null_safety/null_unsafe_app/android/app/src/main/res/values/styles.xml, null_safety/null_unsafe_app/android/build.gradle, null_safety/null_unsafe_app/android/gradle.properties, null_safety/null_unsafe_app/android/gradle/wrapper/gradle-wrapper.properties
Updated both the null_safe_app and null_unsafe_app Android files
=> Update null_safety Android files

navigation_and_routing/android/.gitignore, navigation_and_routing/android/app/build.gradle, navigation_and_routing/android/app/src/main/AndroidManifest.xml, navigation_and_routing/android/app/src/main/res/values-night/styles.xml, navigation_and_routing/android/app/src/main/res/values/styles.xml, navigation_and_routing/android/build.gradle
Clean up and upgrade the Android files for the navigation_and_routing project.
Note that the folder name does not correspond to the app name. `navigation_and_routing` instead of `bookstore`.
=> Update Android files in navigation_and_routing (bookstore)

testing_app/android/build.gradle
This project only needed a more recent version of the kotlin plugin to run on a fresh setup, everything else was up-to-date.
=> Update Kotlin plugin version in testing_app

platform_design/android/.gitignore, platform_design/android/app/build.gradle, platform_design/android/app/src/main/AndroidManifest.xml, platform_design/android/app/src/main/kotlin/dev/flutter/platform_design/MainActivity.kt, platform_design/android/app/src/main/res/drawable-v21/launch_background.xml, platform_design/android/app/src/main/res/values-night/styles.xml, platform_design/android/build.gradle, platform_design/android/gradle.properties, platform_design/android/gradle/wrapper/gradle-wrapper.properties, platform_design/android/settings.gradle
Updated android files for `platform_design` to v2 embedding
=> Update platform_design Android files

provider_counter/android/.gitignore, provider_counter/android/app/build.gradle, provider_counter/android/app/src/main/AndroidManifest.xml, provider_counter/android/app/src/main/kotlin/dev/flutter/provider_counter/MainActivity.kt, provider_counter/android/app/src/main/res/drawable-v21/launch_background.xml, provider_counter/android/app/src/main/res/values-night/styles.xml, provider_counter/android/build.gradle, provider_counter/android/gradle.properties, provider_counter/android/gradle/wrapper/gradle-wrapper.properties, provider_counter/android/settings.gradle
Updated provider_counter project to v2 embedding on Android
=> Update provider_counter Android files

simplistic_calculator/lib/main.dart
Seperate configuraiton data from display.
Also, it now uses constructor tearoffs.
=> Refactoring `simplistic_calculator`

isolate_example/lib/main.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml
Continuing the work in https://github.com/flutter/samples/pull/1028
Set the window title and the window min size.
=> Add desktop window setup to isolate_example

veggieseasons/lib/main.dart, veggieseasons/pubspec.lock, veggieseasons/pubspec.yaml
Added window size setup and title to veggieseasons project.
I went with a fixed mobile-like aspect ratio and resolution.
=> Add window setup to veggie seasons

.github/workflows/scorecards-analysis.yml
This will help us assess the security posture of this repository.
=> Enable scorecards.

desktop_photo_search/fluent_ui/lib/main.dart, desktop_photo_search/material/lib/main.dart
Adds a Quit menu item to exit the app.
=> Photo search: add Quit menu item

desktop_photo_search/fluent_ui/lib/src/widgets/unsplash_search_content.dart, desktop_photo_search/material/lib/src/widgets/unsplash_search_content.dart
=> Dispose `_treeViewScrollController`

tool/flutter_ci_script_beta.sh
=> Elide `desktop_photo_search/fluent_ui` from Beta CI

add_to_app/books/flutter_module_books/pubspec.lock, add_to_app/fullscreen/flutter_module/pubspec.lock, add_to_app/fullscreen/flutter_module/pubspec.yaml, add_to_app/prebuilt_module/flutter_module/pubspec.lock, add_to_app/prebuilt_module/flutter_module/pubspec.yaml, desktop_photo_search/fluent_ui/pubspec.lock, desktop_photo_search/material/pubspec.lock, experimental/federated_plugin/federated_plugin_web/pubspec.lock, experimental/linting_tool/pubspec.lock, experimental/web_dashboard/pubspec.lock, flutter_maps_firestore/pubspec.lock, form_app/pubspec.lock, jsonexample/pubspec.lock, navigation_and_routing/pubspec.lock, place_tracker/pubspec.lock, simplistic_calculator/pubspec.lock, testing_app/pubspec.lock, veggieseasons/pubspec.lock, veggieseasons/pubspec.yaml, web/_tool/pubspec.lock, web/_tool/pubspec.yaml, web/github_dataviz/pubspec.lock
=> `flutter pub upgrade --major-versions`

.github/dependabot.yaml
Adding (I hope) Dependabot version updates automation. 
@jonasfj can you confirm I'm holding the tool right?
Context: https://github.com/github/feedback/discussions/14200
Background: https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/
=> Dependabot version updates

desktop_photo_search/fluent_ui/lib/src/unsplash/unsplash.dart, desktop_photo_search/fluent_ui/macos/Podfile.lock, desktop_photo_search/material/lib/src/unsplash/unsplash.dart, desktop_photo_search/material/macos/Podfile.lock
=> Simplify Unsplash response handling

.github/dependabot.yaml
=> Spread out PR reviews

.github/dependabot.yaml, .github/workflows/main.yml
Context: https://github.com/flutter/codelabs/pull/387
=> Bump GitHub Actions versions

.github/workflows/beta.yml
We are updating a single version to test the theory that when we are
mixing versions and hashes the update is calculated once and reused
across all the files causing the hashes to be replaced with versions.
=> Pin checkout version.

.github/workflows/beta.yml
Pinning `setup-java` with a hash version to fix https://github.com/flutter/samples/pull/1117
=> Pin `setup-java` with a hash

.github/workflows/beta.yml
The pinned version of the checkout was incorrect.
=> Use correct version of checkout.

tool/flutter_ci_script_beta.sh
=> Also elide `desktop_photo_search/material` from Beta CI

place_tracker/lib/place_tracker_app.dart
Fixes https://github.com/flutter/engine/pull/30674 🤌
=> migrate from ui.hash* to Object.hash*

add_to_app/android_view/flutter_module_using_plugin/lib/main.dart, add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart, add_to_app/plugin/flutter_module_using_plugin/lib/main.dart, desktop_photo_search/fluent_ui/lib/src/widgets/policy_dialog.dart, desktop_photo_search/fluent_ui/lib/src/widgets/unsplash_notice.dart, desktop_photo_search/material/lib/src/widgets/policy_dialog.dart, desktop_photo_search/material/lib/src/widgets/unsplash_notice.dart
=> Update for `url_launcher` API change

tool/flutter_ci_script_beta.sh
=> Elide `platform_channels`, `platform_design` & `testing_app` from Beta CI

add_to_app/android_view/flutter_module_using_plugin/lib/main.dart, add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart, add_to_app/plugin/flutter_module_using_plugin/lib/main.dart, analysis_options.yaml, desktop_photo_search/fluent_ui/lib/src/unsplash/unsplash.dart, desktop_photo_search/material/lib/src/unsplash/unsplash.dart, experimental/linting_tool/lib/model/profiles_store.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/repository/hive_service.dart, experimental/linting_tool/lib/widgets/lint_expansion_tile.dart, navigation_and_routing/lib/src/screens/navigator.dart, web/particle_background/lib/simple_animations_package.dart
I'd prefer to have `unawaited_futures` in the mix of lints, just to prevent issue with dropped micro-tasks.
=> Add `unawaited_futures`

.github/workflows/beta.yml, .github/workflows/gh-pages.yml, .github/workflows/verify-web-demos.yml
* Pins the actions/checkout github action to a hash, to increase security
* Resolves a handful of code scan alerts, including:
* https://github.com/flutter/samples/security/code-scanning/35
* https://github.com/flutter/samples/security/code-scanning/36
* https://github.com/flutter/samples/security/code-scanning/37
* https://github.com/flutter/samples/security/code-scanning/38
=> Pin actions/checkout github action

platform_channels/lib/src/add_pet_details.dart, platform_channels/lib/src/event_channel_demo.dart, platform_channels/lib/src/method_channel_demo.dart, platform_channels/lib/src/pet_list_screen.dart, platform_channels/lib/src/platform_image_demo.dart, platform_channels/pubspec.lock, platform_channels/pubspec.yaml, platform_channels/test/src/event_channel_demo_test.dart, tool/flutter_ci_script_beta.sh
Updated `platform_channels` for Dart 2.17
=> [beta-updates] platform_channels

add_to_app/android_view/android_view/build.gradle, add_to_app/books/android_books/build.gradle, add_to_app/fullscreen/android_fullscreen/build.gradle, add_to_app/multiple_flutters/multiple_flutters_android/build.gradle, add_to_app/plugin/android_using_plugin/build.gradle, add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle, android_splash_screen/android/build.gradle
Fixes: https://github.com/flutter/samples/issues/1229
=> Migrate from `jcenter` to `mavenCentral`

provider_counter/pubspec.lock, provider_counter/pubspec.yaml
Updated `provider_counter` for Dart 2.17
=> [beta-updates] provider_counter

platform_channels/lib/src/add_pet_details.dart, platform_channels/lib/src/method_channel_demo.dart
=> Hide state objects

jsonexample/pubspec.lock, jsonexample/pubspec.yaml, jsonexample/windows/flutter/generated_plugins.cmake
Updated `jsonexample` for Dart 2.17
=> [beta-updates] jsonexample

infinite_list/pubspec.lock, infinite_list/pubspec.yaml, infinite_list/windows/flutter/generated_plugins.cmake
Updated `infinite_list` for Dart 2.17
=> [beta-updates] infinite_list

experimental/linting_tool/windows/flutter/generated_plugins.cmake, flutter_maps_firestore/pubspec.lock, flutter_maps_firestore/pubspec.yaml
Updated `flutter_maps_firestore` for Dart 2.17
=> [beta-updates] flutter_maps_firestore

add_to_app/plugin/flutter_module_using_plugin/lib/cell.dart, add_to_app/plugin/flutter_module_using_plugin/lib/main.dart, add_to_app/plugin/flutter_module_using_plugin/pubspec.lock, add_to_app/plugin/flutter_module_using_plugin/pubspec.yaml
Updates `plugin` for Dart 2.17
=> [beta-updates] plugin

experimental/federated_plugin/federated_plugin/example/pubspec.lock, experimental/federated_plugin/federated_plugin/example/windows/flutter/generated_plugins.cmake, experimental/federated_plugin/federated_plugin/pubspec.lock, experimental/federated_plugin/federated_plugin/pubspec.yaml, experimental/federated_plugin/federated_plugin_macos/pubspec.lock, experimental/federated_plugin/federated_plugin_macos/pubspec.yaml, experimental/federated_plugin/federated_plugin_platform_interface/pubspec.lock, experimental/federated_plugin/federated_plugin_platform_interface/pubspec.yaml, experimental/federated_plugin/federated_plugin_web/pubspec.lock, experimental/federated_plugin/federated_plugin_web/pubspec.yaml, experimental/federated_plugin/federated_plugin_windows/pubspec.lock, experimental/federated_plugin/federated_plugin_windows/pubspec.yaml
Updates the `federated_plugin` sample for Dart 2.17
=> [beta-updates] federated_plugin

animations/lib/src/misc/repeating_animation.dart, isolate_example/lib/performance_page.dart, place_tracker/lib/place_details.dart, place_tracker/lib/place_list.dart, place_tracker/lib/place_map.dart, platform_channels/lib/src/pet_list_screen.dart, platform_channels/lib/src/platform_image_demo.dart, veggieseasons/lib/widgets/close_button.dart, veggieseasons/lib/widgets/settings_item.dart, web/charts/lib/gallery_scaffold.dart, web/charts/lib/main.dart, web/github_dataviz/lib/layered_chart.dart, web/github_dataviz/lib/main.dart, web/github_dataviz/lib/timeline.dart
=> Hiding more state objects

platform_view_swift/lib/main.dart, platform_view_swift/pubspec.lock, platform_view_swift/pubspec.yaml
Updated `platform_view_swift` to Dart 2.17
=> [beta-updates] platform_view_swift

android_splash_screen/lib/main.dart, android_splash_screen/pubspec.yaml
Updates `android_splash_screen` for Dart 2.17
=> [beta-updates] android_splash_screen

add_to_app/books/flutter_module_books/lib/main.dart, add_to_app/books/flutter_module_books/pigeon/schema.dart, add_to_app/books/flutter_module_books/pubspec.lock, add_to_app/books/flutter_module_books/pubspec.yaml, add_to_app/books/flutter_module_books/test/widget_test.dart
Updates `flutter_module_books` which still contained null-danger.
=> [beta-updates] flutter module books

add_to_app/fullscreen/flutter_module/pubspec.lock, add_to_app/fullscreen/flutter_module/pubspec.yaml
Updates `fullscreen` app for Dart 2.17
=> [beta updates] fullscreen

add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart, add_to_app/multiple_flutters/multiple_flutters_module/pubspec.lock, add_to_app/multiple_flutters/multiple_flutters_module/pubspec.yaml
Updates `multiple_flutters` to Dart 2.17
=> [beta updates] multiple_flutters

add_to_app/prebuilt_module/flutter_module/lib/main.dart, add_to_app/prebuilt_module/flutter_module/pubspec.lock, add_to_app/prebuilt_module/flutter_module/pubspec.yaml
Updates `prebuilt_module` for Dart 2.17
=> [beta-updates] prebuilt_module

isolate_example/lib/data_transfer_page.dart, isolate_example/lib/infinite_process_page.dart, isolate_example/lib/performance_page.dart, isolate_example/pubspec.lock, isolate_example/pubspec.yaml, isolate_example/windows/flutter/generated_plugins.cmake
Updated `isolate_example` for Dart 2.17
=> [beta-updates] isolate_example

ios_app_clip/lib/main.dart, ios_app_clip/pubspec.lock, ios_app_clip/pubspec.yaml
Updated `ios_app_clip` for Dart 2.17
=> [beta-updates] ios_app_clip

experimental/linting_tool/lib/app.dart, experimental/linting_tool/lib/model/profiles_store.dart, experimental/linting_tool/lib/model/rules_store.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/widgets/adaptive_nav.dart, experimental/linting_tool/lib/widgets/lint_expansion_tile.dart, experimental/linting_tool/lib/widgets/saved_rule_tile.dart, experimental/linting_tool/macos/Podfile.lock, experimental/linting_tool/pubspec.lock, experimental/linting_tool/pubspec.yaml, experimental/linting_tool/windows/flutter/generated_plugins.cmake
Updated linting_tool for Dart 2.17
=> [beta-updates] linting_tool

game_template/lib/src/ads/banner_ad_widget.dart, game_template/lib/src/app_lifecycle/app_lifecycle.dart, game_template/pubspec.lock, game_template/pubspec.yaml
Upgrades everything that is resolvable, and fixes lint warning.
=> Upgrade to latest dependencies

material_3_demo/lib/component_screen.dart, material_3_demo/lib/main.dart
=> Revert "Made elements on component screen stay compact on wider screen"

material_3_demo/lib/component_screen.dart, material_3_demo/lib/main.dart, material_3_demo/test/component_screen_test.dart
=> Made elements on component screen stay compact on wider screen, take 2

.github/workflows/mirror.yml
This is to set main as the default branch.
=> Add mirroring to samples repo.

.github/workflows/main.yml
=> Target CI master -> main

.github/workflows/mirror.yml
Updates default permission of yml to read-only, in order to address this security issue: https://github.com/flutter/samples/security/code-scanning/40
=> Update mirror.yml to default to read only

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/beta.yml, .github/workflows/main.yml, CONTRIBUTING.md, README.md, experimental/veggieseasons/README.md, web/samples_index/lib/src/samples.yaml
=> Update more links and mentions to the main branch

.github/PULL_REQUEST_TEMPLATE.md
=> Fix contributing link

.gitmodules
=> `web/slide_puzzle` remove unmaintained sample

web/samples_index/lib/src/samples.yaml
=> Drop Slide Puzzle's web launch

platform_design/lib/songs_tab.dart, web/_tool/verify_packages.dart
=> Fix beta CI

desktop_photo_search/fluent_ui/lib/main.dart, desktop_photo_search/material/lib/main.dart
Fixes: https://github.com/flutter/samples/issues/1321
Update sample code to match https://github.com/google/flutter-desktop-embedding/pull/903
=> `desktop_photo_search` Break fix

material_3_demo/lib/color_palettes_screen.dart, material_3_demo/lib/component_screen.dart, material_3_demo/lib/elevation_screen.dart, material_3_demo/lib/main.dart, material_3_demo/lib/typography_screen.dart, material_3_demo/test/color_screen_test.dart, material_3_demo/test/component_screen_test.dart, material_3_demo/test/elevation_screen_test.dart, material_3_demo/test/typography_screen_test.dart
This PR adds license headers for all files in M3 demo project.
Fixes #1327
=> Added license headers for M3 demo app

tool/flutter_ci_script_beta.sh
Flutter 3.3.0 beta is introducing a bunch of required changes to pass CI's lint pass
=> Elide projects from beta CI

game_template/lib/main.dart, game_template/lib/src/crashlytics/crashlytics.dart
Updated crashlytics.dart file in Game Template to use 2 APIs introduced in the latest Crashlytics plugin update.
Details here: [New Crash Reporting APIs](https://firebase.blog/posts/2022/07/whats-new-in-crashlytics-for-flutter#new-crash-reporting-apis)
=> New Crashlytics Crash Reporting APIs

desktop_photo_search/codelab_rebuild.yaml
=> `desktop_photo_search` bugfix the rebuild script

platform_channels/.metadata, platform_channels/android/app/build.gradle, platform_channels/android/app/src/debug/AndroidManifest.xml, platform_channels/android/app/src/main/res/values-night/styles.xml, platform_channels/android/app/src/main/res/values/styles.xml, platform_channels/android/app/src/profile/AndroidManifest.xml, platform_channels/android/build.gradle, platform_channels/android/gradle/wrapper/gradle-wrapper.properties, platform_channels/codelab_rebuild.yaml, platform_channels/ios/.gitignore, platform_channels/ios/Flutter/AppFrameworkInfo.plist, platform_channels/ios/Runner.xcodeproj/project.pbxproj, platform_channels/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, platform_channels/ios/Runner/Info.plist
=> `null_safety` rebuild script 

.github/workflows/verify-web-demos.yml
See https://github.com/flutter/samples/pull/1384/checks for an example.
=> Avoid running verify web demos twice

add_to_app/books/flutter_module_books/lib/main.dart
=> Fix `stable` CI

tool/flutter_ci_script_master.sh
=> Fix `master` CI

add_to_app/books/flutter_module_books/pigeon/schema.dart
fixes pigeon file in add-to-app/books
=> [add-to-app/books] Added missing class declarations from the pigeon file

desktop_photo_search/fluent_ui/analysis_options.yaml, desktop_photo_search/fluent_ui/pubspec.yaml, desktop_photo_search/material/analysis_options.yaml, desktop_photo_search/material/pubspec.yaml
=> Pin `window_size` and `menubar`

form_app/lib/src/validation.dart, tool/flutter_ci_script_master.sh
=> Elide `form_app` on `master` CI

game_template/lib/main.dart, game_template/lib/src/audio/audio_controller.dart, game_template/macos/Flutter/GeneratedPluginRegistrant.swift, game_template/pubspec.yaml, game_template/windows/flutter/generated_plugin_registrant.cc, game_template/windows/flutter/generated_plugins.cmake
Upgrades dependencies, including `audioplayers`, `go_router`, and `google_mobile_ads`.
Tested on Android, iOS, macOS and web.
=> Upgrade game_template's dependencies

experimental/material_3_demo/README.md, experimental/material_3_demo/lib/component_screen.dart, experimental/material_3_demo/test/component_screen_test.dart
This pr adds Switch and Checkbox to demo app.
=> Update experimental demo app

game_template/lib/main.dart
This PR is a break-fix for the red CI. Please land after LGTM'ing.
=> Specify parametric type on `buildMyTransition`

tool/flutter_ci_script_beta.sh
=> Elide `experimental/linting_tool` and `simplistic_editor`

desktop_photo_search/fluent_ui/lib/src/widgets/unsplash_search_content.dart, desktop_photo_search/material/lib/src/widgets/unsplash_search_content.dart
=> Fix build breakage

game_template/.gitignore, game_template/pubspec.yaml
There have been some important fixes recently. This fixes #1315.
Also, a fly-by upgrade of two other dependencies.
=> Upgrade audioplayers to latest

tool/flutter_ci_script_beta.sh
=> Elide `form_app` from beta CI

.github/workflows/verify-web-demos.yml
=> Comment out Verify web demos for beta channel

.github/workflows/gh-pages.yml, .github/workflows/verify-web-demos.yml, web/readme.md
=> Switch to using dart run instead of base-VM command

add_to_app/android_view/android_view/app/src/main/java/dev/flutter/example/androidView/FlutterViewEngine.kt
Related issue:  https://github.com/flutter/samples/issues/1488
=> [add_to_app] Fixes type mismatch

game_template/README.md, game_template/pubspec.yaml
Fixes #1494.
Verified that everything works (Android, macOS). Also added a _Troubleshooting_ section to the README, based on previous issues filed by others, and own experience.
=> Upgrade Firebase plugins to next major version

desktop_photo_search/README.md
fixes: https://github.com/flutter/samples/issues/1505
=> Add API key requirement to Photo Search top level

web/samples_index/lib/src/samples.yaml, web/samples_index/lib/src/search.dart, web/samples_index/test/samples_index_test.dart
=> Implement case insensitive search in the samples index

form_app/lib/main.dart, form_app/pubspec.yaml
Adds go_router to the form_app sample.
cc. @domesticmouse @RedBrogdon 
=> Add go_router to form_app

web/_tool/build_ci.dart, web/_tool/peanut_post_build.dart, web/_tool/pubspec.yaml, web/samples_index/.gitignore, web/samples_index/README.md, web/samples_index/analysis_options.yaml, web/samples_index/lib/cookbook.dart, web/samples_index/lib/src/carousel.dart, web/samples_index/lib/src/data.dart, web/samples_index/lib/src/search.dart, web/samples_index/lib/src/templates.dart, web/samples_index/pubspec.yaml, web/samples_index/tool/grind.dart, web/samples_index/web/main.dart, web/samples_index/web/styles.scss
I plan to update the cookbook handling code to be functional again but wanted to do some misc cleanup/updates separate from that work first.
=> Minor sample index cleanup

platform_channels/test/src/add_pet_details_test.dart
=> `platform_channels` make expectation match reality

web/samples_index/lib/cookbook.dart
=> `web/samples_index` breakfix

experimental/material_3_demo/lib/component_screen.dart, experimental/material_3_demo/lib/elevation_screen.dart, experimental/material_3_demo/lib/main.dart, experimental/material_3_demo/test/component_screen_test.dart
In anticipation of a design audit, I went through the whole sample, focusing on components. This PR is a collection of small improvements that would be too small for their own PRs. General goals were consistency, alignment with m3.material.io, and some aesthetic polish. There are a few framework issues for which I've added TODOs and will open corresponding bugs. Adding missing components (e.g. app bar, divider) is out of scope. Of course, I'm open to suggestions.
- add vertical spacing between grouped components
- rebalance lists in 2-list layout
- use same convention for naming, buttons to show components, and usage info
- add tooltips to components when useful
- remove toasts when tapping on things
- display components in rows, with disabled components at the bottom
- simplify buttons …
=> Symposium of small improvements to m3 app

experimental/pedometer/example/lib/steps_repo.dart, experimental/pedometer/example/pubspec.yaml
=> `experimental/pedometer`: fixup linter warning

game_template/pubspec.yaml
Fixes https://github.com/flutter/samples/issues/1590
```console
$ flutter build web
game_template % flutter build web
💪 Building with sound null safety 💪
Compiling lib/main.dart for the Web...                             967ms
```
=> Update to `audioplayers` 3.0.0 in `game_template`

material_3_demo/ios/Flutter/Debug.xcconfig, material_3_demo/ios/Flutter/Release.xcconfig, material_3_demo/ios/Podfile, material_3_demo/lib/color_palettes_screen.dart, material_3_demo/lib/component_screen.dart, material_3_demo/macos/Flutter/Flutter-Debug.xcconfig, material_3_demo/macos/Flutter/Flutter-Release.xcconfig, material_3_demo/macos/Flutter/GeneratedPluginRegistrant.swift, material_3_demo/macos/Podfile, material_3_demo/pubspec.yaml, material_3_demo/test/color_screen_test.dart, material_3_demo/test/component_screen_test.dart, material_3_demo/test/elevation_screen_test.dart, material_3_demo/test/typography_screen_test.dart, material_3_demo/windows/flutter/generated_plugin_registrant.cc, material_3_demo/windows/flutter/generated_plugins.cmake
This PR is to copy the changes in the experimental Material3 demo app and update the stable M3 demo.
=> Update M3 Demo in the Base Directory

place_tracker/lib/place_map.dart, place_tracker/lib/place_tracker_app.dart
Enabled Material 3 on the place_tracker sample.
Some small changes, comments inline.
=> Enable Material 3 on place_tracker

platform_design/lib/main.dart
Enabled Material 3 on platform_design sample
</details>
</details>
=> enable Material 3 on platform_design

testing_app/lib/main.dart, testing_app/lib/screens/home.dart
Enabled Material 3 on testing_app sample.
</details>
</details>
=> Enable Material 3 in `testing_app`

platform_channels/lib/main.dart, platform_channels/lib/src/method_channel_demo.dart, platform_channels/lib/src/platform_image_demo.dart, platform_channels/test/src/platform_image_demo_test.dart
Migrated platform_channels to Material 3
</details>
</details>
=> Migrate `platform_channels` to Material 3

experimental/material_3_demo/lib/component_screen.dart, experimental/material_3_demo/lib/main.dart, material_3_demo/lib/component_screen.dart, material_3_demo/lib/main.dart
Fixes: https://github.com/flutter/samples/issues/1642
Reverts flutter/samples#1630
=> Revert "Improvements to M3 demo app"

tool/flutter_ci_script_master.sh
=> Elide failing projects from `master` CI

.github/dependabot.yaml
=> Update project directories for `dependabot`

animations/lib/main.dart, animations/lib/src/misc/flutter_animate.dart, animations/lib/src/misc/misc.dart, animations/pubspec.yaml
=> `animations`: Add `flutter_animate`

google_maps/android/app/src/main/AndroidManifest.xml, google_maps/ios/Runner/AppDelegate.swift, google_maps/web/index.html
Removed API key from sample code. Invalidated key in Firebase.
=> Fix API key issue

experimental/material_3_demo/web/index.html, material_3_demo/.metadata, material_3_demo/web/index.html
=> material_3_demo: update web scaffold to latest

tool/flutter_ci_script_shared.sh
Copied from https://github.com/flutter/codelabs/pull/1506
- [?] All existing and new tests are passing.
=> Use `dart test`

google_maps/lib/main.dart
=> `google_maps`: Tidyup code formatting

deeplink_store_example/pubspec.yaml
Update the go_router version that contains a fixes
=> Updates go_router version used in deeplink store example

analysis_defaults/lib/flutter.yaml
=> Add `unnecessary_breaks` lint

desktop_photo_search/fluent_ui/pubspec.yaml
=> Fix `desktop_photo_search/fluent_ui`

tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_master.sh
=> Break fix CI

.github/dependabot.yaml
Follow up to https://github.com/flutter/samples/pull/1773
=> Update dependabot.yaml for web_embedding sample

experimental/federated_plugin/federated_plugin/example/test/widget_test.dart, experimental/federated_plugin/federated_plugin/test/federated_plugin_test.dart, experimental/federated_plugin/federated_plugin_platform_interface/test/federated_plugin_platform_interface_test.dart, tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_master.sh
Replaces https://github.com/flutter/samples/pull/1749
FYI @negotoyolo
=> Fixup `experimental/federated_plugin`

.github/dependabot.yaml
Take only security and major version updates for the `ng-flutter` sample.
(Similar to what's done [here](https://github.com/flutter/packages/blob/main/.github/dependabot.yml#L33-L35))
* Fixes https://github.com/flutter/samples/issues/1809
_See [docs about the `update-types` dependabot setting](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore)._ …
=> [ci] Reduce npm update noise.

web/samples_index/lib/src/data.dart, web/samples_index/lib/src/data.g.dart, web/samples_index/pubspec.yaml
Updates build dependencies as well as other constraints to more closely match versions used.
Supersedes https://github.com/flutter/samples/pull/1814
=> Update samples index dependencies and constraints

.github/workflows/main.yml
fixes: https://github.com/flutter/samples/issues/1825
Note: the added check is expected to fail until https://github.com/flutter/samples/pull/1826 is landed
=> Add a CI check for `web/samples_index`

web/samples_index/lib/src/samples.yaml
This PR is required to land for I/O Connect Miami next week.
Context: https://github.com/flutter/samples/pull/1824#discussion_r1198062978
=> Fix up `web/samples_index` configuration for `next_gen_ui_demo`

next_gen_ui_demo/web/manifest.json
=> `next_gen_ui_demo`: display in landscape when loaded as a PWA

next_gen_ui_demo/lib/main.dart
=> `next_gen_ui_demo`: Add restart button

tool/flutter_ci_script_master.sh, veggieseasons/pubspec.yaml
Investigating https://github.com/flutter/samples/issues/1838
=> `veggieseasons`: Pin `go_router` version

.github/workflows/scorecards-analysis.yml
Fix the currently failing workflow on `main` - https://github.com/flutter/samples/actions/runs/5077854629/jobs/9121639667
=> Update github/codeql-action from 2.3.4 to 2.3.5 to fix error

game_template/lib/src/audio/audio_controller.dart, tool/flutter_ci_script_master.sh
=> `game_template` fix up exhaustive checks

tool/flutter_ci_script_master.sh
=> Elide `game_template` from master CI

game_template/README.md, game_template/ios/Podfile, game_template/ios/Runner.xcodeproj/project.pbxproj, game_template/ios/Runner.xcworkspace/contents.xcworkspacedata, game_template/lib/main.dart, game_template/macos/Podfile, game_template/macos/Runner.xcodeproj/project.pbxproj, game_template/macos/Runner.xcworkspace/contents.xcworkspacedata
Disallow navigating to /win without details.
Fixes #1288.
=> Fix web navigation bug in game_template

game_template/lib/main.dart
Fixes #1551.
Also, remove superfluous `debugPrint` calls and other `Logger` setup since the latest `pkg:logging` does this stuff automatically and so the setup lead to duplicate messages in console.
=> Provide LocalKey to every custom transition

next_gen_ui_demo/lib/common/shader_effect.dart
=> `next_gen_ui_demo`: Stop `Picture`s leaking

next_gen_ui_demo/lib/common/shader_effect.dart, next_gen_ui_demo/pubspec.yaml
=> `next_gen_ui_demo`: Add `dispose` handler for `Picture`s

platform_channels/test/src/event_channel_demo_test.dart, platform_channels/test/src/pet_list_screen_test.dart
Replaces deprecated APIs in unit tests.
Fixes https://github.com/flutter/samples/issues/1765
=> Update `platform_channels` for 3.10

tool/flutter_ci_script_master.sh
=> Add tracking issues

tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_master.sh
=> CI maintenance

tool/flutter_ci_script_master.sh
=> Elide `simplistic_editor` from master CI

provider_shopper/README.md
fixes: https://github.com/flutter/samples/issues/1026
=> Drop broken link

google_maps/android/app/build.gradle, google_maps/android/build.gradle, google_maps/ios/Runner.xcodeproj/project.pbxproj, google_maps/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, google_maps/ios/Runner.xcworkspace/contents.xcworkspacedata, google_maps/lib/main.dart
Enable material m3 in this app  and added minSdkVersion 20 to fix a small bug.
before enabling material 3 android and iOS screenshots
After enabling material 3 android and iOS screenshots
=> enable material m3 into google_maps example app

experimental/material_3_demo/lib/component_screen.dart, material_3_demo/lib/component_screen.dart
*Reopen #1740 . Has the test been fixed? Appreciate it🙏*
=> Reopen #1740 Fix dialog text

tool/flutter_ci_script_master.sh
=> Elide `simplistic_editor`

add_to_app/books/android_books/app/build.gradle
```
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter] /Users/zero/Dev/GitHub/samples/add_to_app/books/flutter_module_books/.android/Flutter/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 19,
or use tools:overrideLibrary="dev.flutter.example.flutter_module_books" to force usage (may lead to runtime failures)
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: …
```
=> Fixes minSdkVersion compile error

tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_master.sh
Fixed by https://github.com/shyndman/flutter_layout_grid/pull/92
=> `simplistic_calculator` fixed

experimental/linting_tool/lib/theme/app_theme.dart, simplistic_editor/lib/basic_text_field.dart, simplistic_editor/lib/basic_text_input_client.dart
=> Update `Simplistic_Editor` to support OCR context menu button

web_embedding/README.md
Update README.md of the `web_embedding` sample to include links to community contributions.
* Follow up of: https://github.com/flutter/samples/pull/1945
=> [web_embedding] Update README to link to our first community contribs.

platform_channels/ios/Runner.xcodeproj/project.pbxproj
Adds the AccelerometerStreamHandler to Runner. For some reason, the reference of file was not included in project.pbxproj. 
Fixes: #1981 
=> Fixes platform_channel sample

google_maps/.metadata, google_maps/README.md, google_maps/android/app/build.gradle, google_maps/ios/Podfile, google_maps/lib/main.dart, google_maps/pubspec.yaml
- Update dependencies and minimum OS versions to latest
- Add info window to the marker
- Add a README
Fixes #1983
=> Update `google_maps` sample

web_embedding/ng-flutter/README.md, web_embedding/ng-flutter/package-lock.json, web_embedding/ng-flutter/package.json
The main goal was to resolve some security alerts being triggered on the repository, but I also updated angular and verified the sample continues to work.
Resolved security alerts:
- https://github.com/flutter/samples/security/dependabot/3
- https://github.com/flutter/samples/security/code-scanning/45 (https://github.com/advisories/GHSA-c2qf-rxjj-qqgw, https://github.com/advisories/GHSA-353f-5xf4-qw67)
=> Update ng-flutter to resolve security alerts

.github/dependabot.yaml
This is adding the autosubmit label to prs created by dependabot.
=> Enable autosubmit for samples repo.

experimental/material_3_demo/lib/color_palettes_screen.dart, experimental/material_3_demo/test/color_screen_test.dart, material_3_demo/lib/color_palettes_screen.dart, material_3_demo/test/color_screen_test.dart
Re-arrange colors according to [Baseline color scheme tokens]
[Baseline color scheme tokens]: https://m3.material.io/styles/color/the-color-system/tokens#e26e130c-fa67-48e1-81ca-d28f6e4ed398
=> Add surfaceTint, outlineVariant, scrim and re-arrange

experimental/material_3_demo/lib/component_screen.dart, material_3_demo/lib/component_screen.dart
This PR is to fix the warning which is mentioned in #2079
=> Remove extra parameter from `BottomSheet`

web_embedding/ng-flutter/README.md, web_embedding/ng-flutter/angular.json, web_embedding/ng-flutter/package-lock.json, web_embedding/ng-flutter/package.json, web_embedding/ng-flutter/src/app/app.component.ts, web_embedding/ng-flutter/src/index.html, web_embedding/ng-flutter/src/main.ts
This should also fix the dependabot security alert currently open against the repository (https://github.com/flutter/samples/security/dependabot/8).
=> Update ng-flutter embedding example to Angular v17

animations/lib/src/basics/animation_controller.dart, experimental/pedometer/lib/health_connect.dart, experimental/pedometer/lib/pedometer_bindings_generated.dart, game_template/macos/Flutter/GeneratedPluginRegistrant.swift, simplistic_editor/lib/basic_text_input_client.dart, tool/flutter_ci_script_beta.sh, tool/flutter_ci_script_master.sh
=> Update for `beta` channel

web/samples_index/lib/src/samples.yaml
=> Drop Next Gen UI demo from Samples index

add_to_app/fullscreen/android_fullscreen/app/build.gradle, add_to_app/fullscreen/android_fullscreen/app/src/debug/AndroidManifest.xml, add_to_app/fullscreen/android_fullscreen/app/src/main/AndroidManifest.xml, add_to_app/fullscreen/android_fullscreen/build.gradle, add_to_app/fullscreen/android_fullscreen/gradle/wrapper/gradle-wrapper.properties
Where AGP == Android Gradle plugin
Upgrade carried out by Android Studio upgrade wizard
=> Upgrade `android_fullscreen` to AGP 7.4.2

README.md
=> Drop retired Flutter Developer Google group

add_to_app/multiple_flutters/multiple_flutters_android/gradle/wrapper/gradle-wrapper.properties
=> `add_to_app/multiple_flutters` Update Gradle version

code_sharing/shared/lib/src/models.freezed.dart, code_sharing/shared/lib/src/models.g.dart, experimental/linting_tool/lib/pages/saved_lints_page.dart, experimental/linting_tool/lib/widgets/lint_expansion_tile.dart, platform_channels/lib/src/method_channel_demo.dart, veggieseasons/lib/screens/settings.dart
=> Fixups for master CI

simplistic_editor/lib/basic_text_field.dart, simplistic_editor/lib/basic_text_input_client.dart, tool/flutter_ci_script_master.sh
=> Add implementations for onShare and onSearchWeb

web/_tool/build_ci.dart
Follow up to https://github.com/flutter/samples/pull/2144
cc: @kevmoo
=> Update ignored directories in gh-pages step

add_to_app/README.md
Fixes https://github.com/flutter/flutter/issues/143550
=> Add debugging details to  `add_to_app` sample README.

material_3_demo/lib/component_screen.dart, material_3_demo/pubspec.yaml
Add some icons
Fix component names
=> [material_3_demo] bump min SDK, move time and date components together

material_3_demo/test/component_screen_test.dart
It's not yet clear to me what in https://github.com/flutter/samples/commit/e5f3bacaf8f45a0e96c3a85ee078aee6bc4c5931 is causing the failure, but this resolves it.
=> Fix tests after recent M3 demo changes

desktop_photo_search/fluent_ui/lib/src/widgets/unsplash_search_content.dart, desktop_photo_search/material/lib/src/widgets/unsplash_search_content.dart, tool/flutter_ci_script_master.sh
=> Deal with Master CI failures

tool/flutter_ci_script_beta.sh, web_embedding/ng-flutter/flutter/analysis_options.yaml, web_embedding/ng-flutter/flutter/lib/main.dart, web_embedding/ng-flutter/flutter/lib/pages/counter.dart, web_embedding/ng-flutter/flutter/lib/pages/dash.dart, web_embedding/ng-flutter/flutter/lib/pages/text.dart, web_embedding/ng-flutter/flutter/lib/src/js_interop.dart, web_embedding/ng-flutter/flutter/lib/src/js_interop/helper.dart, web_embedding/ng-flutter/flutter/pubspec.yaml, web_embedding/ng-flutter/package.json
No functional change, just while I was verifying it still works with the latest Angular releases, completed some cleanup as well.
=> Clean up ng-flutter a bit

dynamic_theme/README.md, dynamic_theme/lib/main.dart, gemini_tasks/README.md
Adds `README.md` files to the dynamic_theme and gemini_tasks projects. Also removes a block of commented-out code from one of them.
=> Adds missing READMEs to dynamic_theme, gemini_tasks

gemini_tasks/lib/main.dart
- Fix typo
- Remove unused code.
=> Fix typo and remove unused code

add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle
=> Smallest change to get android ci to pass

add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle, add_to_app/prebuilt_module/android_using_prebuilt_module/app/src/main/java/dev/flutter/example/androidusingprebuiltmodule/MainActivity.kt, add_to_app/prebuilt_module/android_using_prebuilt_module/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, add_to_app/prebuilt_module/android_using_prebuilt_module/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml, add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle, add_to_app/prebuilt_module/android_using_prebuilt_module/gradle.properties, add_to_app/prebuilt_module/android_using_prebuilt_module/gradle/wrapper/gradle-wrapper.properties
- **Update gradle**
- **Update dependencies**
- **revert test:runner, espresso and test:core to versions specified in https://github.com/flutter/packages/tree/main/packages/espresso**
- **fix or suppress issues found in gradlew check**
Partial fix for #2346 
=> Update android dependencies 

material_3_demo/lib/component_screen.dart, material_3_demo/test/component_screen_test.dart, tool/flutter_ci_script_master.sh, tool/flutter_ci_script_stable.sh, tool/flutter_clean_packages
This PR is to include `CarouselView` to M3 demo app.
https://github.com/user-attachments/assets/7db76c06-aa7e-4461-9baa-51fd5c4e6b38
=> Flutter 3.24 update, Add CarouselView examples to demo 3

add_to_app/README.md
=> remove outdated links at bottom of README

add_to_app/fullscreen/README.md
=> explicitly say how to launch the app for iOS

veggieseasons/lib/styles.dart
updating font to more closely align with system font
=> Update font to match Cupertino

add_to_app/README.md
=> matching issue tracker to top-level samples README

.github/workflows/beta.yml, .github/workflows/main.yml, ai_recipe_generation/lib/features/prompt/prompt_screen.dart, ai_recipe_generation/lib/features/prompt/widgets/image_input_widget.dart, ai_recipe_generation/lib/features/recipes/saved_recipes_screen.dart, ai_recipe_generation/lib/features/recipes/widgets/recipe_display_widget.dart, ai_recipe_generation/lib/router.dart, ai_recipe_generation/lib/util/tap_recorder.dart, ai_recipe_generation/lib/widgets/add_image_widget.dart, ai_recipe_generation/lib/widgets/filter_chip_selection_input.dart, ai_recipe_generation/lib/widgets/highlight_border_on_hover_widget.dart, ai_recipe_generation/lib/widgets/marketplace_button_widget.dart, experimental/linting_tool/lib/theme/app_theme.dart, game_template/macos/Flutter/GeneratedPluginRegistrant.swift, material_3_demo/lib/component_screen.dart, simplistic_editor/lib/basic_text_input_client.dart
On the `master` branch, `withOpacity` is deprecated.
Use `withAlpha` instead
=> CI Fix, part #2

veggieseasons/README.md
Remove the AppStore link as the app was unpublished.
=> Update veggie seasons README.md

tool/flutter_ci_script_beta.sh
=> Elide `ios_app_clip` from beta CI

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md
Adds sample index to readme.
Completes #2497 
Completes #2536
=> Update readme, add changelog

README.md
Fix invalid [contributor's guide] links found in the `README.md` file.
=> Fix Broken Links in README.md

compass_app/app/pubspec.yaml
Mostly updates share_plus from v7 to v10.
=> Update compass app client dependencies

web/samples_index/lib/src/carousel.dart, web/samples_index/web/description.dart, web/samples_index/web/main.dart
See https://github.com/flutter/samples/issues/2582
=> Ignore dart:html deprecation for now

compass_app/app/lib/data/repositories/booking/booking_repository_local.dart, compass_app/app/pubspec.yaml, compass_app/server/lib/routes/booking.dart, compass_app/server/pubspec.yaml, experimental/web_dashboard/.gitignore, experimental/web_dashboard/pubspec.yaml, form_app/.gitignore, navigation_and_routing/.gitignore, navigation_and_routing/lib/main.dart, navigation_and_routing/pubspec.yaml, place_tracker/.gitignore, place_tracker/lib/place_map.dart, place_tracker/pubspec.yaml, simplistic_editor/.gitignore
Drop dep on pkg:collection, use new bits in Dart 3.0
Fixed very old dep in navigation_and_routing – bug was fixed long ago
=> Clean up dependencies across packages

experimental/date_planner/README.md
=> Update old date_planner README.md

navigation_and_routing/README.md
*Formatting markdown provide a link to docs.*
=> Update links Navigation Routing

.github/workflows/beta.yml, .github/workflows/main.yml
=> Revert "Bump subosito/flutter-action from 2.19.0 to 2.20.0"

.github/dependabot.yaml, .github/workflows/beta.yml, .github/workflows/main.yml
=> Revert "Bump subosito/flutter-action from 2.19.0 to 2.20.0" again
