flutter/samples

- shrine/lib/app.dart
- shrine/lib/backdrop.dart
- shrine/lib/category_menu_page.dart
- shrine/lib/main.dart
- shrine/lib/model/app_state_model.dart
This updates the Shrine app so that category selection and filtering work properly with the scoped model code already introduced for the shopping cart.
Due to the way the Backdrop's closing animation was triggered, this change has the unfortunate side effect of forcing the user to manually close the back layer after choosing a category. That'll need to be corrected in the next PR.
> Fixing unchangeable Shrine categories.

- place_tracker/README.md
These instructions are on the google_map_flutter plugin's README, but it is beneficial to have them here, too.
> Update README to include API Key instructions.

- place_tracker/pubspec.yaml
A breaking API change is coming in 0.1.0, setting a dependency constraint
to keep the place_tracker sample building.
> Set google_maps_flutter's version to <=0.1.0 in place_tracker.

- veggieseasons/lib/data/local_veggie_provider.dart
- veggieseasons/lib/data/preferences.dart
- veggieseasons/lib/screens/settings.dart
- veggieseasons/lib/widgets/settings_group.dart
- veggieseasons/lib/widgets/settings_item.dart
Adds refactored versions of SettingsItem and SettingsGroup from @xster's demo, as well as a functional main settings screen and two routes for settings details.
> Fleshes out settings screen with groups, items, and navigation

- veggieseasons/lib/data/local_veggie_provider.dart
- veggieseasons/lib/data/veggie.dart
- veggieseasons/lib/screens/details.dart
- veggieseasons/lib/styles.dart
- veggieseasons/lib/widgets/trivia.dart
Adds a finished trivia widget that appears alternately with veggie facts and info on the details page. Right now there are questions for Apples alone. I'll add more questions once we've verified that the UI/UX works this way.
> Adds trivia to Veggie details screen

- veggieseasons/lib/screens/list.dart
- veggieseasons/lib/styles.dart
- veggieseasons/lib/widgets/veggie_card.dart
You'll have to exercise some artistic taste on top of this but it looks like this
Fixes https://github.com/flutter/flutter/issues/30737
Tangentially fixes https://github.com/flutter/flutter/issues/30511
> Make in-season and not-in-season cards different

- scoped_model_counter/lib/main.dart
- scoped_model_counter/pubspec.yaml
- scoped_model_counter/test/widget_test.dart
This is the minimal possible change. It is meant to be readable as a standalone Pull Request.
This does not touch comments. Additionally, it doesn’t use the niceties of provider, like automatic disposal of the model. Lastly, it doesn’t even rename the project from `scoped_model_counter`. All that will come in a follow-up PR.
> Migrate from scoped_model to provider

- provider_counter/test/widget_test.dart
Since we’re not using `(_)` anywhere else in this example, doing this here is weird.
> Make use of (context) consistent

- place_tracker/lib/place_map.dart
- travis_script.sh
- veggieseasons/lib/screens/list.dart
- veggieseasons/lib/styles.dart
- veggieseasons/lib/widgets/veggie_card.dart
The current Travis script will only print offending files, but won’t fail the build. Added `--set-exit-if-changed` to fix that.
Also, simplified the call from using `grep` and `xargs` to simple `flutter format .`, which recurses directories.
Lastly, fixed offending files that needed `dartfmt`. (But not in the directories that aren’t covered by `travis_script.sh`.
> Ensure flutter format and fix offending files

- customer_testing
- customer_testing.bat
Scripts for the new tests repo:
https://github.com/flutter/tests.
These scripts will be used to test DevRel's samples with new versions of the Flutter SDK in order to detect regressions in backward compatibility.
> Added new test scripts

- jsonexample/README.md
- jsonexample/analysis_options.yaml
- jsonexample/build.yaml
- jsonexample/lib/built_value/built_complex_object.g.dart
- jsonexample/lib/built_value/built_simple_object.g.dart
- jsonexample/lib/json_serializable/serializable_complex_object.g.dart
- jsonexample/lib/json_serializable/serializable_simple_object.g.dart
- jsonexample/pubspec.lock
- jsonexample/pubspec.yaml
This updates the json sample with the latest tooling and re-runs the generator.
I ran into an issue where the generated files don't play nicely with the `implicit-dynamic: false` flag in analysis_options.yaml. Normally, this wouldn't be a problem, since we are excluding the generated files in analysis_options.yaml, but those files still seem to be included when IntelliJ and the dartanalyzer command run. Strangely, `flutter analyze` succeeds. I've filed an issue for this [here](https://github.com/dart-lang/sdk/issues/38753). 
Since this doesn't break CI and the app still works, this is probably OK to merge.
> jsonexample maintenance

- web/gallery/pubspec.yaml
This was causing the preview image to not get built and displayed on https://flutter.github.io/samples/
> add preview image to gallery assets

- experimental/README.md
- experimental/add_to_app/README.md
In `experimental/add_to_app` it references that CocoaPods needs to be updated, however there is no mention on this README of how one should proceed to do so.
As such, instructions have been added.
If needed, the following can also be added:
"To verify that you have the latest version, you can run the command:
```bash
pod --version
```
And check with the [latest releases](https://github.com/CocoaPods/CocoaPods/releases) of CocoaPods."
> Add CocoaPods installation to the README

- travis_script.sh
Ensure that the CI checks run on the gallery now that 1.12 is in the stable channel
> Enable CI checks to run on the gallery

- gallery/gallery/lib/l10n/gallery_localizations.dart
- gallery/gallery/lib/l10n/intl_en_US.arb
- gallery/gallery/lib/l10n/intl_en_US.xml
- gallery/gallery/lib/l10n/messages_en_US.dart
- gallery/gallery/lib/pages/home.dart
The study back button takes you back to the gallery and so the semantic label reflects that now.
Closes [#480](https://github.com/material-components/material-components-flutter-gallery/issues/480)
> Update semantic label of study back button to better explain the action

- gallery/gallery/macos/Flutter/GeneratedPluginRegistrant.swift
- gallery/gallery/pubspec.lock
- gallery/gallery/pubspec.yaml
This PR removes unnecessary url_launcher pubspec entries, now that web and mac support are included in the plugin
> Remove unnecessary url_launcher pubspec entries

- gallery/gallery/tool/grind.dart
This defaults the script to set 'en_US' for the default locale for the gallery application.
Related to https://github.com/flutter/flutter/pull/47845
> [Gallery] Modify grinder script to use preferred ordered locales

- .travis.yml
- add_to_app/android_fullscreen/app/build.gradle
- add_to_app/android_using_plugin/app/build.gradle
- add_to_app/android_using_prebuilt_module/app/build.gradle
- add_to_app/flutter_module/lib/main.dart
- add_to_app/flutter_module/test/widget_test.dart
- add_to_app/flutter_module_using_plugin/lib/main.dart
- add_to_app/flutter_module_using_plugin/test/widget_test.dart
- travis_script.sh
Updates our Travis-based CI setup to:
* Format, analyze, and test the two add-to-app flutter modules.
* Build all three Android add-to-app projects in debug and release modes to verify that they actually build.
This has put some additional work into our tests, which is slowing them down. It may be possible to parallelize things more than what's done here, but that's fodder for another PR.
No iOS/Xcode testing is being done here, either, so that's a task still outstanding.
> Configuring travis to build Android.

- gallery/gallery/lib/pages/demo.dart
Since the desktop layout includes the black flutter banner, we don't need to include the top safe area.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/522
**Before:**
**After:**
> [Gallery] Remove top safe area from demo screen for desktop layout

- gallery/gallery/lib/demos/cupertino/cupertino_activity_indicator_demo.dart
- gallery/gallery/lib/demos/cupertino/cupertino_slider_demo.dart
- gallery/gallery/lib/demos/cupertino/cupertino_switch_demo.dart
- gallery/gallery/lib/demos/material/bottom_app_bar_demo.dart
- gallery/gallery/lib/demos/material/progress_indicator_demo.dart
Forgot to do this for recently added demos now that they aren't separate MaterialApps
> Remove back button from demo appbars

- gallery/gallery/lib/studies/shrine/expanding_bottom_sheet.dart
Closes https://github.com/material-components/material-components-flutter-gallery/issues/472
**Before:**
**After:**
> [Gallery] Account for safe area for shrine shopping cart on mobile

- .travis.yml
- tool/travis_android_script.sh
- tool/travis_flutter_script.sh
* Creates a top-level tool directory.
* Moves the travis script into it.
* Forks travis script into two, one for pure Flutter, one for Android app builds.
- These will be joined by a third for iOS stuff.
* Updates `.travis.yml` to use 2x2 jobs, with channel and script type as the dimensions.
> Sharding travis jobs

- INDEX.md
Matt Carroll's flutter_ui_challenge stuff doesn't exist any more, so the search linked here ends up being blank.
Remove the reference and link.
> index: Remove stale link

- gallery/gallery/lib/studies/shrine/backdrop.dart
- gallery/gallery/macos/Podfile.lock
App bar semantics in Shrine:
**Before:**
* heading
* close menu button
* shrine
* search button
* settings button
**After:**
* shrine heading
* close menu button
* search button
* settings button
Closes https://github.com/material-components/material-components-flutter-gallery/issues/485
I also included the macos Podfile.lock since git kept showing it as a diff anytime you build for macOS.
> [Gallery] Remove extra semantic node from shrine app bar

- gallery/gallery/lib/layout/highlight_focus.dart
- gallery/gallery/lib/studies/crane/app.dart
- gallery/gallery/lib/studies/crane/backdrop.dart
- gallery/gallery/lib/studies/crane/backlayer.dart
- gallery/gallery/lib/studies/crane/eat_form.dart
- gallery/gallery/lib/studies/crane/fly_form.dart
- gallery/gallery/lib/studies/crane/header_form.dart
- gallery/gallery/lib/studies/crane/item_cards.dart
- gallery/gallery/lib/studies/crane/sleep_form.dart
This PR implements focus (to the best of my ability) for Crane. All elements are accessible via the tab key, however, there is an unsolved ordering problem which causes the destinations to be navigated through before the form fields. 
Closes https://github.com/material-components/material-components-flutter-gallery/issues/324
> [Gallery] Crane focus

- gallery/gallery/lib/pages/demo.dart
Enable copy to clipboard for web, as it now exists on Flutter master channel.
Also update the argument for the `_showSnackBarOnCopyFailure` as we otherwise got the error/warning message:
```
'Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: (Exception) => Null'
```
Closes https://github.com/material-components/material-components-flutter-gallery/issues/516
> [Gallery] Enable copy to clipboard on web for code examples, now enabled on Flutter master channel

- gallery/gallery/lib/main.dart
- gallery/gallery/lib/pages/backdrop.dart
- gallery/gallery/lib/pages/settings.dart
- gallery/gallery/test/pages/home_test.dart
Adding animation to settings backdrop, includes the following changes:
- Lift up AnimationController to parent widget AnimatedBackdrop so it can be shared with child widgets.
- Make the boolean 'isSettingsOpen' a ValueNotifier so we can listen to changes for it in SettingsPage.
- When closing settings, also shrink expanded setting.
- Animate the settings page to slide in from above.
- Animate the settings item to stagger when the panel is opened.
See gif for animation:
https://github.com/material-components/material-components-flutter-gallery/issues/24
> [Gallery] Add animation for settings backdrop

- gallery/gallery/lib/main.dart
- gallery/gallery/lib/pages/settings.dart
- gallery/gallery/pubspec.lock
- gallery/gallery/pubspec.yaml
I've published a new package flutter_localized_locales, that we'll use instead of relying on my fork of flutter_localized_countries.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/526
https://github.com/material-components/material-components-flutter-gallery/issues/527
> [Gallery] Use new package flutter_localized_locales

- gallery/gallery/lib/pages/about.dart
Since https://github.com/flutter/flutter/pull/48929 landed this is not needed anymore.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/251
> [Gallery] Remove hardcoded strings that were a workaround for raw string problem

- gallery/gallery/lib/pages/settings_list_item.dart
Small change that causes SettingsListItem content not to be removed unnecessarily from the tree based on whether it should be visible
https://github.com/material-components/material-components-flutter-gallery/issues/346
> Don't remove SettingsListItem content from tree

- gallery/README.md
- gallery/gallery/android/app/src/profile/AndroidManifest.xml
- gallery/gallery/ios/Runner.xcodeproj/project.pbxproj
- gallery/gallery/macos/Runner/Configs/AppInfo.xcconfig
Closes https://github.com/material-components/material-components-flutter-gallery/issues/514
> [Gallery] Use io.flutter as organization instead of placeholder

- gallery/gallery/lib/studies/shrine/app.dart
- gallery/gallery/lib/studies/shrine/expanding_bottom_sheet.dart
Move up `WillPopScope` above `MaterialApp` to make sure that when the expanding bottom sheet (cart) is open, it will close the sheet instead of going back when pressing the back button on Android.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/519
> [Gallery] Close Shrine cart on back button press for android

- gallery/gallery/lib/pages/demo.dart
TLDR: Fixes a bugs on both desktop and mobile which caused demo state to be reset. 
This was caused by rendering different trees; on mobile: based on whether the options/info panels were open; on desktop, based on whether the demo was in fullscreen. Additionally on desktop, it seemed that conditionally rendering the sized box (or container) preceding the demoContent caused the demoContent widget to be fully rebuilt. Instead, I always specify its width.
This PR also removes width calculations, instead specifying a max width for info and options panes. This incidentally causes the demoContent to remain the same width regardless of the chosen section on desktop. The demoContent grows with the screen size, as before. The section on the left grows until the specified max width.
Closes …
> [Gallery] Preserve demo state, simplify demo width calculations on desktop

- gallery/gallery/lib/pages/demo.dart
This adds a bit of padding after the actions for the last ripple to be visible
Closes https://github.com/material-components/material-components-flutter-gallery/issues/208
> [Gallery] Add padding to demo appBar

- gallery/gallery/lib/studies/shrine/login.dart
- gallery/gallery/lib/studies/shrine/supplemental/product_card.dart
- We do not need to read out the Shrine logo for screen readers (from the a11y talk on Flutter Interact: https://youtu.be/bWbBgbmAdQs?t=849).
- On VoiceOver we do not read onTapHint, so I changed it to hint.
Closes https://github.com/material-components/material-components-flutter-gallery/issues/483
> [Gallery] Exclude semantics for logo and change to hint for products on Shrine

- .github/no-response.yml
Adds a configuration for the No Response GitHub bot.
q.v. https://github.com/probot/no-response
> Adds no-response config

- gallery/gallery/lib/studies/shrine/home.dart
- gallery/gallery/lib/studies/shrine/shopping_cart.dart
Add OrdinalSortKeys to Semantics label to try to force the screen reader to start form the top of the shopping cart. It does not always seem to be respected (https://github.com/material-components/material-components-flutter-gallery/issues/390) but this was the best I could do.
> [Gallery] Add OrdinalSortKey to Shrine shopping cart

- gallery/gallery/lib/layout/adaptive.dart
- gallery/gallery/lib/studies/crane/backdrop.dart
- gallery/gallery/lib/studies/crane/header_form.dart
Closes https://github.com/material-components/material-components-flutter-gallery/issues/137
This change:
* Define `isSmallDesktop` for Crane to be isDesktop + less than 1000 width
* Modifies textfield layout to use two columns when `isSmallDesktop`
* Modifies crane padding when `isSmallDesktop` to use the mobile padding instead.
> [Gallery] Modify desktop layout for crane when running in "Small desktop" size

- gallery/gallery/lib/pages/home.dart
- gallery/gallery/lib/pages/settings_list_item.dart
Fixes a bug with the slow motion setting a11y announcement
> [Gallery] Fix slow motion setting announcement

- provider_shopper/lib/main.dart
- provider_shopper/lib/models/cart.dart
- provider_shopper/pubspec.lock
- provider_shopper/pubspec.yaml
The addresses feedback from https://github.com/flutter/samples/issues/245. Instead of constructing a new `CartModel`, we merely update the `catalog` field.
We no longer need a fancy constructor, and `CartModel._catalog` cannot be final any more.
This change also upgrades to `pkg:provider` 4.0.2, just to stay on top of things (it's was a no-op in the case of this sample).
> Follow best practice of ProxyProvider updating

- animations/pubspec.yaml
- experimental/desktop_photo_search/pubspec.yaml
- gallery/pubspec.yaml
- place_tracker/pubspec.yaml
- platform_design/pubspec.yaml
- platform_view_swift/pubspec.yaml
- provider_counter/pubspec.yaml
In reference to this PR in flutter repo 
https://github.com/flutter/flutter/pull/50479#issuecomment-585304558
> Update cupertino_icons dependency from 0.1.2 to 0.1.3

- gallery/README.md
- gallery/pubspec.yaml
Update README with steps to create a release
> [Gallery] Update README with steps to create a release

- animations/lib/src/basics/06_custom_tween.dart
text on MaterialButton was not changing from 'Write Essay' to 'Delete Essay' and vice versa because setState was never called
> Fix - text on MaterialButton not changing

- veggieseasons/lib/main.dart
We still have plenty of work to do for #322, so this PR is a stopgap. It hardcodes the brightness level in `CupertinoApp` to light, effectively ignoring the OS dark mode setting.
This isn't a great state to be in, and work on #322 should still be prioritized.
> Disable dark mode for Veggieseasons

- gallery/lib/studies/crane/backdrop.dart
closes #349 
Fixed screenshot:
> Fix Crane example searchbar margin

- platform_design/lib/main.dart
- platform_design/lib/news_tab.dart
- platform_design/lib/widgets.dart
I've fixed all the problems related to dark mode in #376.
I've simply changed the color property of the problem causing widgets to grab from the current theme.
Please have a look @RedBrogdon @johnpryan.
iOS:
Android:
> [platform_design]Fix problems in dark mode

- experimental/web_dashboard/lib/src/app.dart
- experimental/web_dashboard/lib/src/auth/auth.dart
- experimental/web_dashboard/lib/src/auth/firebase.dart
- experimental/web_dashboard/lib/src/auth/mock.dart
- experimental/web_dashboard/lib/src/pages/home.dart
- experimental/web_dashboard/lib/src/pages/sign_in.dart
- experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart
This adds a logout button, a widget to switch between the login page and app page, and makes the the sign in screen call the `onSuccess` callback immediately if the user is already signed in (for example if they sign in and refresh the page, they are taken directly to the app and not asked to click the sign in button.)
The `MockAuthService`'s method,  `isSignedIn`, always returns false, so the sign in button needs to be pressed each time the app loads if using this configuration.
> [web_dashboard] add logout

- web/_tool/peanut_post_build.dart
- web/samples_index/tool/grind.dart
The previous `build-release` task doesn't generate the index file.
Fixes #455
> Run full sample index build when running peanut

- provider_shopper/lib/common/theme.dart
Code of other files depends on `headline1`, but there's only `headline2` defined in the **theme.dart** file.
> Code of other files depends on `headline1`

- place_tracker/ios/Runner/Info.plist
To use this plugin on iOS you need to opt-in for the embedded views preview by adding a boolean property to the app's Info.plist file, with the key io.flutter.embedded_views_preview and the value YES.
<key>io.flutter.embedded_views_preview</key>
<true/>
> fix ios install

- platform_channels/README.md
Updates README for the platform_channels sample.
> [platform_channels] updates README

- testing_app/README.md
- Modified the testing guide.
- Added instructions for running tests using only the Flutter SDK.
- Added information about CI/CD.
- Tweaked a few other small things.
@domesticmouse, please take a look.
@RedBrogdon, this is probably the last PR before we merge the `testing_sample` branch into `master`. Now might be a good time to take a look at the project.
> [testing_app] Update the README and simplify the testing guide

- platform_channels/lib/main.dart
Actually, the imports in `platform_channels/lib/main.dart` weren't sorted in `master`. So, I was accepting the current change. It was totally out of my mind that it would again cause a conflict when merging back to `master`.
@domesticmouse, it should probably work now =)
> Resolve conflicts caused when trying to merge testing_sample into master

- testing_app/lib/models/favorites.dart
- testing_app/lib/screens/home.dart
- testing_app/test_driver/perf_test.dart
@CareF,
As mentioned in #500, I've made the following changes to improve the scrolling perf test:
- Increased `itemCount` from `50` to `100` in the `ListView`
- Set `cacheExtent` to `20`
- Used `scroll()` to scroll down and back up with `dy` : `-7000` and `7000` and duration of `1` second
Let me know if anything needs to be changed. I'm able to make changes faster and in an easier way here.
/cc: @domesticmouse
> [testing_app] Change scrolling approach for perf_test

- MAINTENANCE.md
* Removes the individual entries for web/ and experimental/ (web is too large, and experimental apps should be getting steady enough contribution that maintenance is handled that way).
* Removes entry for gallery, which is no longer in the repo.
* Adds new lines for samples that have come into the repo since our last maintenance jam.
> Updating maintenance log

- gallery/README.md
Removes the README file that used to direct people from the Flutter Gallery's old location in this repo to the new location in flutter/gallery.
The gallery remains reachable from the visual samples index, which is the intended point of discovery for all samples.
> Removing gallery redirect

- experimental/add_to_app/README.md
We are several months removed from when the app graduated from experimental, so this can be taken out now.
> Removing add_to_app redirect file

- CONTRIBUTING.md
Hello, I found out that the link of **Flutter's code of conduct** in [CONTRIBUTING.md](https://github.com/flutter/samples/blob/master/CONTRIBUTING.md)  leads to style guide for Flutter repo.
This PR updates the link to use the correct URL.
> Update link of code of conduct

- add_to_app/README.md
- add_to_app/ios_fullscreen/IOSFullScreen.xcodeproj/project.pbxproj
- add_to_app/ios_using_plugin/IOSUsingPlugin.xcodeproj/project.pbxproj
- add_to_app/ios_using_prebuilt_module/IOSUsingPrebuiltModule.xcodeproj/project.pbxproj
- tool/travis_ios_script.sh
Update add-to-app sample to use XCFrameworks instead of universal frameworks.
Universal (fat) frameworks that support physical devices and simulators aren't possible in an ARM simulator world since the arm64 `iphoneos` and `iphonesimulator` slices can't be `lipo`d together in the same binary.  Prefer `--xcframework` in expectation of that switch.
See https://github.com/flutter/flutter/issues/69718, https://github.com/flutter/flutter/issues/69733, and overall macOS ARM support at https://github.com/flutter/flutter/issues/60118
> Use xcframeworks in prebuilt add-to-app sample

- web/samples_index/lib/src/search.dart
- web/samples_index/test/samples_index_test.dart
- web/samples_index/tool/grind.dart
- web/samples_index/web/description.dart
Fixes #392 
Currently, the search results are inaccurate when type filters are used. I've fixed this by adding an additional type check before the current checks. This loop will check whether a type parameter is present in the search query, and return false if the current self type mismatches the query type. Hope this helps :)
I've tested this against a set of custom queries, and the following is a screenshot when tested against the query mentioned in the issue.
`?search=ios&type=cookbook`
> [samples_index] Fix search bug when using filters

- add_to_app/flutter_module/lib/main.dart
- add_to_app/ios_fullscreen/IOSFullScreen/ViewController.swift
Not sure why we left in un-animated originally. API's on stable.
> let add-to-app ios demo page transitions be animated

- experimental/veggieseasons/lib/main.dart
- experimental/veggieseasons/lib/screens/details.dart
- experimental/veggieseasons/lib/screens/favorites.dart
- experimental/veggieseasons/lib/screens/list.dart
- experimental/veggieseasons/lib/screens/search.dart
- experimental/veggieseasons/lib/styles.dart
- experimental/veggieseasons/lib/widgets/settings_group.dart
- experimental/veggieseasons/lib/widgets/settings_item.dart
- experimental/veggieseasons/lib/widgets/trivia.dart
- experimental/veggieseasons/lib/widgets/veggie_card.dart
- experimental/veggieseasons/lib/widgets/veggie_headline.dart
This was done to handle styling in a manner more in keeping with current SDK capabilities. (Issue #322 )
> Styling revamp using CupertinoThemeData and CupertinoTextThemeData

- web/samples_index/lib/src/carousel.dart
- web/samples_index/web/styles.scss
Currently, the carousel doesn't render well when no images or only one image is present. This will solve this issue by 
* Skipping the carousel container space when no images are present
* Rendering only the image without carousel options when only one image is present
I missed this case in the implementation, and fixed asap I noted
> [samples_index] Fix carousel edge cases and make mobile responsive

- testing_app/README.md
Added instructions to generate test coverage report with the help of the `lcov` tool.
closes: #611
> [testing_app] Add instructions to generate test coverage report

- animations/lib/src/basics/01_animated_container.dart
- animations/lib/src/basics/02_page_route_builder.dart
- animations/lib/src/basics/03_animation_controller.dart
- animations/lib/src/basics/04_tweens.dart
- animations/lib/src/basics/05_animated_builder.dart
- animations/lib/src/basics/06_custom_tween.dart
- animations/lib/src/basics/07_tween_sequence.dart
- animations/lib/src/basics/08_fade_transition.dart
- animations/lib/src/misc/animated_list.dart
- animations/lib/src/misc/animated_positioned.dart
- animations/lib/src/misc/animated_switcher.dart
- animations/lib/src/misc/expand_card.dart
- animations/lib/src/misc/hero_animation.dart
- animations/lib/src/misc/physics_card_drag.dart
Issue- #564 
Is it good or anything needs to be changed?
> [Animation] Added title to Animation Demos

- isolate_example/README.md
Some files were renamed in f325e685d148
but the rename never made it to the README.
> isolate_example: Update filenames in README.md

- add_to_app/ios_fullscreen/IOSFullScreen.xcodeproj/project.pbxproj
- add_to_app/ios_using_plugin/IOSUsingPlugin.xcodeproj/project.pbxproj
- add_to_app/ios_using_prebuilt_module/IOSUsingPrebuiltModule.xcodeproj/project.pbxproj
Allow iOS add-to-app host apps to run on Apple Silicon devices by explicitly excluding arm64 from the valid archs to run.
All add-to-app hosts will need to do this until https://github.com/flutter/flutter/issues/64502 and friends are complete.
Website documentation: https://github.com/flutter/website/pull/5174
> Exclude arm64 from simulator iOS add-to-app host app archs

- experimental/veggieseasons/lib/screens/search.dart
- experimental/veggieseasons/test/restoration_test.dart
Restoration of the search page broke in https://github.com/flutter/samples/pull/433/commits/c7d3f1a55a7606d5442ff4141fb1754ad469d2eb due to a bad merge. Embarrassingly, that part of the search page wasn't covered by the test, so the breakage went unnoticed at the time. This PR fixes the breakage and extends the test so it will hopefully never break again.
> Fix restoration of search page

- provider_counter/lib/main.dart
Wrong usage of Provider.of<T> may be misleading for beginners.
> Fix generic type placement of Provider.of call

- experimental/veggieseasons/ios/Runner/Base.lproj/Main.storyboard
Feature was implemented in https://github.com/flutter/engine/pull/23495.
This enables it for the veggie seasons app according to the instructions to be published in https://github.com/flutter/flutter/pull/73585.
To test state restoration on iOS:
1. Open `ios/Runner.xcworkspace/` in xcode.
2. (iOS 14+ only): Switch to build in profile or release mode (launching an app from the home screen is not supported in debug mode), see screenshots in https://github.com/flutter/flutter/issues/51673#issuecomment-597215128.
2. Press the Play button in xcode to build and run the app.
3. Create some in-memory state in the app on the phone, e.g. by navigating to a different screen.
4. Background the app on the phone, e.g. by goign back to the home screen.
5. Press the Stop button in xcode to terminate the …
> Enable State Restoration for iOS

- ios_app_clip/test/widget_test.dart
- place_tracker/lib/main.dart
- place_tracker/lib/place.dart
- place_tracker/lib/place_details.dart
- place_tracker/lib/place_list.dart
- place_tracker/lib/place_map.dart
- place_tracker/lib/place_tracker_app.dart
- place_tracker/lib/stub_data.dart
- place_tracker/test/widget_test.dart
- platform_design/lib/main.dart
- platform_design/lib/news_tab.dart
- platform_design/lib/profile_tab.dart
- platform_design/lib/settings_tab.dart
- platform_design/lib/song_detail_tab.dart
- platform_design/lib/songs_tab.dart
- platform_design/lib/utils.dart
- platform_design/lib/widgets.dart
- platform_design/test/widget_test.dart
Fixes: #649 
I have added the headers that were missing in the files. Also, most of the apps in [web](https://github.com/flutter/samples/tree/master/web) are having their own licenses. So, I have not added this header in the files of those apps. Let me know if is is required I will fix that up also. 
Please review and suggest changes @ditman @johnpryan :)
> fix: added headers

- add_to_app/android_fullscreen/app/build.gradle
Reverts flutter/samples#662
Looks like the Github Action platform has reverted the available NDK version: https://github.com/flutter/samples/pull/668/checks?check_run_id=1746329483#step:5:418
> Revert "Bump ndk"

- experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart
- navigation_and_routing/lib/nav_1/on_generate_route.dart
I've fixed the following warnings
1. In `/experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart` -> title parameter is depricated after v1.19.0
2. In `/navigation_and_routing/lib/nav_1/on_generate_route.dart` -> all fields of the `DetailScreen` class should be marked as final
Hope these changes would be helpful, :)
> Fix minor warnings

- .github/workflows/main.yml
This allows the exit code to be returned to GitHub Actions
> use source script.sh instead of ./script.sh

- web/samples_index/web/styles.scss
Fixes #683 
Fixes #684 
Fixes #690 
Currently, the carousel overlays with the launch app and source code buttons, and some tags. This will fix those alignment issues and make the buttons and tags clickable.
> Fix carousel alignment issue

- experimental/desktop_photo_search/lib/main.dart
- experimental/desktop_photo_search/lib/src/widgets/about_dialog.dart
- web/samples_index/lib/src/samples.yaml
- web/samples_index/pubspec.yaml
As the `form_app` is moved out of the experimental directory. Therefore, I have updated the URL inside the `samples_index` too.
Also, I have removed the extra line at the end of pubspec.yaml.
> [samples_index] updated source code url for form_app

- README.md
I wanted to try an example, and I didn't manage to clone the repository or download the zip, because the repository is very big and the connection hang up. So I discovered I can use svn to download a single example. Perhaps it can be useful for others too.
> README.md: how to download a single example

- experimental/veggieseasons/lib/data/preferences.dart
- experimental/veggieseasons/lib/screens/settings.dart
- experimental/veggieseasons/lib/styles.dart
Added the `Restore Defaults` option in the settings menu.  The idea is to incorporate a feature that makes sense for adding a `CupertinoAlertDialog` in the app.
Related Issue #546 
Screenshot:
> [VeggieSeasons] added restore defaults feature

- testing_app/lib/screens/favorites.dart
- testing_app/lib/screens/home.dart
- testing_app/pubspec.lock
Fixed Issue #658 
cc: @domesticmouse, @RedBrogdon
> Updated testing_app for upcoming release

- add_to_app/README.md
Fixed a typo in add-to-app/README.md. Changed 'Fluter' to 'Flutter'.
> [add-to-app] Fixed typo in README.md

- web/particle_background/README.md
Refer #708 
Owner of the [simple_animations](https://github.com/felixblaschke/simple_animations) repository said that the example has now moved 
to https://github.com/felixblaschke/simple_animations/tree/2.4.2/example.
I have changed the link in README.md .
> Update link in README.md of web/particle_background

- animations/ios/Runner.xcodeproj/project.pbxproj
- animations/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- animations/lib/main.dart
- animations/lib/src/basics/01_animated_container.dart
- animations/lib/src/basics/03_animation_controller.dart
- animations/lib/src/basics/04_tweens.dart
- animations/lib/src/basics/05_animated_builder.dart
- animations/lib/src/basics/06_custom_tween.dart
- animations/lib/src/basics/07_tween_sequence.dart
- animations/lib/src/basics/08_fade_transition.dart
- animations/lib/src/misc/animated_list.dart
- animations/lib/src/misc/animated_positioned.dart
- animations/lib/src/misc/animated_switcher.dart
- animations/lib/src/misc/card_swipe.dart
- animations/lib/src/misc/carousel.dart
- animations/lib/src/misc/curved_animation.dart
- animations/lib/src/misc/hero_animation.dart
- animations/lib/src/misc/physics_card_drag.dart
- animations/lib/src/misc/repeating_animation.dart
- animations/pubspec.lock
- animations/pubspec.yaml
* Ups the SDK minimum for `/animations` to 2.12.0-0
* Migrates all the code
* Changes the animated list sample from using indexes to identify records to using IDs.
* Updates pubspec.(yaml|lock)
Comments especially welcome on the changes for migration.
> [beta branch] Migrate animation sample

- add_to_app/fullscreen/android_fullscreen/app/build.gradle
Removes the hardcoded NDK version. If this doesn't work, I'll bump it to the most recent available one instead.
> Fixes broken Android build settings for android_fullscreen

- .github/workflows/beta.yml
Turns out it's not possible to do a nightly cron-job of a workflow for any branch but master, which explains why I've been getting daily emails about our beta CI workflow failing due to errors that only exist in the master branch of the code.
> Removing scheduled run of beta CI workflow

- add_to_app/android_view/app/build.gradle
> No version of NDK matched the requested version 21.3.6528147. Versions available locally: 21.4.7075529, 21.4.7075529, 21.4.7075529
https://github.com/flutter/samples/pull/677/checks?check_run_id=1923183048#step:5:430
Looks like the migration to GitHub actions made hardcoding these unnecessary in CI.
Fixes https://github.com/flutter/samples/issues/737
> Remove ndkVersion and buildToolsVersion version from add_to_app/android_view

- tool/ios_ci_script.sh
The `xcpretty` gem used to prettyprint the output of `xcodebuild` has been masking error codes and causing tests to pass even when builds fail. This PR sets `pipefail` in the iOS CI script, fixing the issue.
> Unmasking CI error codes from iOS

- web/readme.md
Flutter 2 makes the web stable. Therefore, I have updated the readme file inside the web directory containing steps to run the web project. 
@johnpryan PTAL and suggest changes if any.
> Updated readme for web

- add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt
fixes https://github.com/flutter/samples/issues/762
> fixed crash if you back out of 2 double engine activities

- veggieseasons/lib/screens/search.dart
On MacOS, typing backspace in the search space did not work because the hidden search box was taking focus.
cc @tusharojha
> [veggieseasons] Fix search backspace when no results

- navigation_and_routing/lib/router/router.dart
- navigation_and_routing/lib/router_advanced/nested_router.dart
- navigation_and_routing/lib/router_advanced/transition_delegate.dart
- navigation_and_routing/pubspec.lock
Some methods of the Router API support asynchronous processing. However, if the information is available synchronously, it's best to just return a SynchronousFuture to indicate that (also documented, e.g. here: https://master-api.flutter.dev/flutter/widgets/RouterDelegate/setNewRoutePath.html). 
What's the difference? Let's say we link directly to `/book/1`. When `parseRouteInformation` is async, the Router will render for one frame the home page `/` because the Future returned by `parseRouteInformation` with the correct route information will not complete until the next frame. When the future then complete in the next frame, `/book/1` is rendered as expected.
When `parseRouteInformation` returns a SynchronousFuture, the information that `/book/1` should be rendered is available in the …
> Change router examples to use SynchronousFuture

- experimental/federated_plugin/federated_plugin/test/federated_plugin_test.dart
- flutter_maps_firestore/lib/main.dart
- jsonexample/test/widget_tests_test.dart
- platform_channels/lib/main.dart
- platform_channels/test/home_page_test.dart
- platform_design/lib/widgets.dart
- platform_design/test/widget_test.dart
The dev channel's analyzer caught some poorly sorted imports, and was complaining. This should fix the dev channel tests and be a no-op for stable and beta.
> Sorting imports in federated_plugin and others

- tool/flutter_ci_script_shared.sh
Changes the `ci_projects` function in `flutter_ci_script_shared.sh` to use the `-o none` option in place of the deprecated `-n` when testing with the dev channel.
> Adding new flag for dev channel format

- web/_tool/build_ci.dart
This [ci run](https://github.com/flutter/samples/runs/3020311936) failed, but the deploy script continued and deployed an empty gh-pages branch. 
This changes makes sure that `_tool/build_ci.dart` exits if a sub-process fails (specifically if `grind deploy` in the `samples_index` directory fails)
This doesn't make any changes to the GitHub Actions workflow - I'm not 100% sure that future steps will be skipped if one of the steps fails, so we might need to make a change to `gh-pages.yml`.
> Exit the sample index deployment CI script if a sub-process fails

- web/_tool/build_ci.dart
- web/_tool/fix_base_tags.dart
- web/charts/pubspec.lock
- web/filipino_cuisine/pubspec.lock
- web/github_dataviz/pubspec.lock
Each sample's `<base>` tag needs to point to the path the app is being hosted at. This creates a tool that runs after each sample is built to fix these tags.
This is currently causing the [navigation_and_routing](https://flutter.github.io/samples/navigation_and_routing.html) sample to break
> Fix <base href="/"> tags in hosted samples, if required.

- navigation_and_routing/lib/src/app.dart
This is needed to show transition animations when the web app is running on desktop platforms: https://github.com/flutter/flutter/issues/82053
cc: @darrenaustin
> Reverts navigation_and_routing animation behavior to be based on the platform

- add_to_app/books/README.md
Hi, it seems this folder is extra and it's not needed in the bash script.
> Remove extra ios_books in bash code

- form_app/lib/src/http/mock_client.dart
- form_app/lib/src/sign_in_http.dart
- form_app/lib/src/validation.dart
- form_app/pubspec.lock
- form_app/pubspec.yaml
- form_app/test/form_app_test.dart
- form_app now uses `mockito ^5.0.0`.
- fix MockClient implementation.  The Mock definition was missing the named parameter 'headers', so the mock response wasn't returned.
- Add a test for `SignInHttpDemo`.
Fixes #897
> Update mockito in form_app

- form_app/pubspec.yaml
Required changed for the form_app to build and launch on the iPhone 12 Pro Max - IOS 14.5 simulator. I didn't test it elsewhere.
> Updated the dart english_words package to 4.0.0

- platform_design/analysis_options.yaml
- platform_design/lib/main.dart
- platform_design/lib/news_tab.dart
- platform_design/lib/profile_tab.dart
- platform_design/lib/settings_tab.dart
- platform_design/lib/song_detail_tab.dart
- platform_design/lib/widgets.dart
- platform_design/test/widget_test.dart
In attempting to enforce `use_key_in_widget_constructors` in `platform_design` I trip over a failing test. And I have no idea why adding unused `Key` params and various `const` declarations changes the behaviour of the program under test. 
Please explain?
```console
$ flutter test
00:04 +0: Can change platform correctly                                              
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: exactly one matching node in the widget tree
Actual: _WidgetTypeFinder:<zero widgets with type "CupertinoSliverNavigationBar" (ignoring
offstage widgets)>
Which: means none were found but one was expected
When the exception was thrown, this was the stack:
#4 …
```
> `platform_design`: Enforce `use_key_in_widget_constructors`

- form_app/ios/Flutter/AppFrameworkInfo.plist
- form_app/lib/src/form_widgets.dart
@johnpryan, this was a small issue that came in recently, so I just hopped on it. It looks like an unused type parameter on one of the widget classes was weirding up a callback's inferred type, making it dynamic and producing a console warning.
* Removes the type param from the `_FormDatePicker` class.
* Changes the nullability of the fields in that class to make them non-nullable.
* Updates minimum iOS version, which is an artifact of building with Flutter 2.5.
Fixes #932.
> Removed FormDatePicker type param.

- .github/workflows/gh-pages.yml
Write permissions are needed so that [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) can commit to the gh-pages branch.
To verify, I restricted the permissions, and loosened them in the YAML to simulate the configuration flutter/samples uses:
Example run from my fork of this repo: https://github.com/johnpryan/flutter_samples/runs/4073943383
Resolves #914
> Specify workflow permissions for build-and-deploy action

- testing_app/integration_test/app_test.dart
- testing_app/lib/screens/favorites.dart
- testing_app/lib/screens/home.dart
- testing_app/test/favorites_test.dart
As requested by @domesticmouse @johnpryan  I did a code review of the testing_app code sample.
I've added small code improvements:
- Using Provider's extension functions with `read` and `watch`.
- Using `const` and `final` when possible.
- Adding some trailing commas for better code formatting.
Also have a question regarding the code I saw.
In the file `integration_test/app_test.dart` some calls to `pumpAndSettle` have a `Duration` set of one second. What is the purpose of those? I think they can be removed. But I guess having the `Duration` set helps to see the test running "in action". Maybe that should be documented in a comment? Just to not to encourage developers to add `Duration` when it may not be required.
cc. @RedBrogdon
> testing_app code review and improvements

- add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/EngineBindings.kt
Since https://github.com/flutter/engine/pull/24644 is on stable, we can uncomment it now.
> Ensure that the engine is destroyed when 'EngineBindings.detach' in the multiple_flutters example on Android

- experimental/desktop_photo_search/lib/src/widgets/photo_details.dart
Adds the Unsplash photo description, if available, as the image
semantics label in the photo detail view.
Adds a 'download' tooltip to the download IconButton, which also sets
the semantics label for screen readers.
> Photo search: Add image, download button semantics

- experimental/desktop_photo_search/linux/my_application.cc
Sets the window title on Linux to "Desktop Photo Search".
> Photo search: update Linux window title

- add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/AndroidManifest.xml
Add an example code for custom switch leak VM settings, issue link:
* https://github.com/flutter/flutter/issues/95903
Related PR:
* https://github.com/flutter/engine/pull/30541
> Add the leak_vm meta-data in add-to-app sample

- add_to_app/multiple_flutters/multiple_flutters_android/app/build.gradle
- add_to_app/multiple_flutters/multiple_flutters_android/build.gradle
I was trying to run the `multiple_flutters_android` sample (https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters/multiple_flutters_android) on my Android device with Android Studio following the instructions in the readme and I ran into two problems:
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
> The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.window:window-java:1.0.0-beta04.
AAR metadata file: …
```
> Fix multiple_flutters_android

- .github/workflows/beta.yml
- add_to_app/android_view/android_view/app/build.gradle
- add_to_app/android_view/android_view/build.gradle
- add_to_app/books/android_books/app/build.gradle
- add_to_app/books/android_books/build.gradle
- add_to_app/fullscreen/android_fullscreen/app/build.gradle
- add_to_app/fullscreen/android_fullscreen/build.gradle
- add_to_app/fullscreen/flutter_module/pubspec.lock
- add_to_app/multiple_flutters/multiple_flutters_module/pubspec.lock
- add_to_app/plugin/android_using_plugin/app/build.gradle
- add_to_app/plugin/android_using_plugin/build.gradle
- add_to_app/plugin/flutter_module_using_plugin/pubspec.lock
- add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle
- add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle
- add_to_app/prebuilt_module/flutter_module/pubspec.lock
Readies us for the next release.
* Updates pubspecs as necessary.
* Bumps Android SDK versions and Kotlin versions.
* Removes the dev channel tests from beta workflow.
* Also removes superfluous "beta-on-beta" tests.
> Lands beta changes.

- web/samples_index/lib/src/templates.dart
Restores the Google Analytics snippets that were lost during the migration to GitHub actions.
> Google Analytics restoration

- .gitmodules
This bumps the transitive dependency on `platform` to the latest version, which works against the current stable version of Flutter, and should unblock the deploy CI job.
> Working slide_puzzle

- desktop_photo_search/fluent_ui/lib/main.dart
- desktop_photo_search/material/lib/main.dart
Switches to using an elipsis character instead of three periods.
Eliminates the elipsis after 'About'. This appears to be consistent
across operating systems:
From Apple's Human Interface guidelines:
Use an ellipsis whenever choosing a menu item requires additional input
from the user. The ellipsis character (…) means a dialog or separate
window will open and prompt the user for additional information or to
make a choice.
From Microsoft's UI guidelines:
An ellipsis should be used "only when additional information is required
to perform the action. For example, the commands About, Advanced, Help,
Options, Properties, and Settings must display another window when
clicked, but don't require additional information from the user.
Therefore they don't need ellipses."
Ref: …
> Photo search: minor menu item text cleanup

- animations/lib/src/misc/carousel.dart
**Description**
Overriding `scrollBehavior` on `PageView` so it will work on Flutter web, importing `import 'dart:ui';` for adding `PointerDeviceKind.mouse,` as dragDevice.
**Issues**
#964 
**Tests**
> Enable mouse scrolling on Carousel sample

- desktop_photo_search/fluent_ui/lib/main.dart
- desktop_photo_search/fluent_ui/pubspec.lock
- desktop_photo_search/fluent_ui/pubspec.yaml
Continuing the work in https://github.com/flutter/samples/pull/1028
Here, I have only added the min window size. The window title seems to be from the native code, and since this is a desktop app, the window size is not limited by a maximum size.
From my tests, a minimum 1024 x 800 is necessary, so the UI is not cut off.
Interestingly, this project also contained another desktop only plugin as git reference (the menubar)
> Add min window size to fluent_ui desktop app

- desktop_photo_search/material/lib/main.dart
- desktop_photo_search/material/pubspec.lock
- desktop_photo_search/material/pubspec.yaml
Same as https://github.com/flutter/samples/pull/1036 but for the Material project sample
> Add setupWindow with min size to Material desktop photo search

- provider_counter/lib/main.dart
- provider_counter/pubspec.lock
- provider_counter/pubspec.yaml
Continuing the work in https://github.com/flutter/samples/pull/1028
The app is setup to maintain a mobile-like window size, relatively small since it is just the counter default example. Also adds window title.
> Add window setup to provider_counter

- navigation_and_routing/lib/main.dart
- navigation_and_routing/pubspec.lock
- navigation_and_routing/pubspec.yaml
Continuing the work in https://github.com/flutter/samples/pull/1028
In this case the app is setup to maintain a mobile-like window size.
> Add window desktop setup to navigation_and_routing

- simplistic_calculator/lib/main.dart
The project already had the window_size plugin in it, so adding the window min size was just a matter of finding trial and error.
The UI scales, but some buttons will be too small under 600x500.
Example at 600x500.
> Add min window size to simplistic_calculator

- animations/lib/main.dart
- desktop_photo_search/fluent_ui/lib/main.dart
- desktop_photo_search/material/lib/main.dart
- form_app/lib/main.dart
- infinite_list/lib/main.dart
- isolate_example/lib/main.dart
- jsonexample/lib/main.dart
- null_safety/null_safe_app/lib/main.dart
- provider_shopper/lib/main.dart
Following the styleguide: https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters
This PR renames all the `kWindowWidth` and `kWindowHeight` const to `windowWidth` and `windowHeight`
> Rename const - don't use prefixes

- desktop_photo_search/fluent_ui/lib/src/unsplash/unsplash.dart
- desktop_photo_search/material/lib/src/unsplash/unsplash.dart
Tested on both Windows and macOS, http package's Response#body is by default interpreted as latin1. Unsplash sends search results as UTF8 but with no content type specified, so we must "manually" decode `bodyBytes`.
Before:
After:
> Force utf8-decoding of Unsplash reponse (#586 & #590)

- README.md
I recently learned about partial clones from [this article](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/), so I think we should be recommending that instead of shallow clones.
I also ran `git-sizer` on this repo, which found some large images. Fortunately, they can be removed since they're unused.
> Recommend partial clone instead of shallow clone, remove unused blobs

- add_to_app/books/ios_books/Podfile
- add_to_app/fullscreen/ios_fullscreen/Podfile
- add_to_app/multiple_flutters/multiple_flutters_ios/Podfile
- add_to_app/plugin/ios_using_plugin/Podfile
Add-to-app host `Podfile`s will be required to call `flutter_post_install(installer)` when https://github.com/flutter/flutter/pull/101943 merges.  The addition of `defined?(flutter_post_install)` will allow `pod install` to succeed on versions of Flutter that do not yet have `flutter_post_install` available.
Hold until https://github.com/flutter/flutter/pull/101943 merges.
> Add-to-app iOS flutter_post_install post_install hook

- .github/workflows/beta.yml
- .github/workflows/gh-pages.yml
- .github/workflows/main.yml
- .github/workflows/verify-web-demos.yml
This PR adds read-all default permissions to github workflow templates that don't already have a default set.
This fixes a handful of security issues:
* https://github.com/flutter/samples/security/code-scanning/27
* https://github.com/flutter/samples/security/code-scanning/26
* https://github.com/flutter/samples/security/code-scanning/25
* https://github.com/flutter/samples/security/code-scanning/24
* https://github.com/flutter/samples/security/code-scanning/23 …
> Add read-all default permission to remaining github workflows templates

- tool/flutter_ci_script_beta.sh
Hey @Renzo-Olivares, it appears that `simplistic_editor` needs some formatting changes for Flutter beta. I want to drop it from the beta CI to clean up the errors, and then we can follow this PR with a clean up PR for beta changes.
brett
> `simplistic_editor` is failing on beta CI

- tool/android_ci_script.sh
This is required because gradle-wrapper.jar isn't checked in.
For more: https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:adding_wrapper
> Download the Gradle wrapper in CI checks

- null_safety/null_safe_app/pubspec.lock
- null_safety/null_safe_app/windows/flutter/generated_plugins.cmake
- null_safety/null_unsafe_app/pubspec.lock
- null_safety/null_unsafe_app/pubspec.yaml
- null_safety/null_unsafe_app/windows/flutter/generated_plugins.cmake
Bumped dependencies for `null_unsafe_app`
Does not increase Dart SDK past 2.12, for obvious reasons
> [beta-updates] null_unsafe_app

- material_3_demo/lib/component_screen.dart
- material_3_demo/lib/main.dart
This PR changed the layout on the first screen so that elements on the screen will compact themselves on a wider screen, such as web version.
Before
Now
> Made elements on component screen stay compact on wider screen

- simplistic_editor/lib/basic_text_input_client.dart
- simplistic_editor/lib/main.dart
- simplistic_editor/lib/toggle_buttons_state_manager.dart
Encoding the bold, italic, underline state as a List<bool> is performant but opaque. I'm attempting to introduce an informative abstraction that makes the code a bit more understandable.
I don't think I've broken the API, it appears to work when I test the app. I'd like to get confirmation that this change is both sane and correct.
> `simplistic_editor` Making `ToggleButtonState` more obvious

- game_template/pubspec.yaml
Bumps `firebase_crashlytics` to `2.8.1`, as the old version wasn't building on macOS.
Fixes #1287
> game_template dependencies

- .github/workflows/gh-pages.yml
- web/_tool/build_ci.dart
- web/_tool/peanut_post_build.dart
The standalone pub tool has been replaced with subcommands under the `flutter` or `dart` executables.
> Fix some web tool pub issues

- game_template/lib/main.dart
Link in comments section of [main.dart](https://github.com/flutter/samples/blob/main/game_template/lib/main.dart) doesn't exist. Updated it to direct users to the Crashlytics section of the main [README.md](https://github.com/flutter/samples/blob/main/game_template/README.md) file instead. 
> updatedCrashlytics link in main.dart

- simplistic_editor/lib/main.dart
If I understand the code correctly, there appears to be redundant `ToggleButtonsStateManager` instances in the tree. There are three instances, all with the same configuration, with two instances underneath a single higher instance. I'm guessing all three wind up with identical state. I hope.
Or am I misunderstanding the intent of the structure?
> Drop redundant `ToggleButtonsStateManager` instances

- simplistic_editor/lib/main.dart
- simplistic_editor/lib/text_editing_delta_history_manager.dart
Similar to https://github.com/flutter/samples/pull/1305
> Pull up `TextEditingDeltaHistoryManager` to drop redundancy

- game_template/lib/main.dart
Without these changes to the package import statements, a user who enables the FirebaseCrashlytics code in main.dart of game_template, they will see a list of errors.
These are the changes I had to make to get rid of the errors. 
@domesticmouse @johnpryan - please advise if this causes any problems or if there is a better way to do this.
> Changes to package import statements to prevent errors when using FirebaseCrashlytics code

- desktop_photo_search/fluent_ui/pubspec.yaml
- desktop_photo_search/material/pubspec.yaml
- experimental/linting_tool/pubspec.yaml
As of 0.9.1, all of the 1P implementations of `file_selector` are
endorsed, so there's no need to directly include the sub-packages.
> Remove `file_selector_*` from pubspecs.

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/test/component_screen_test.dart
Instead of using ElevatedButton with filled, filled tonal style, this pr shows FilledButton and FilledButton.tonal without extra style configuration.
> Update filled button and filled tonal button

- .github/workflows/scorecards-analysis.yml
Bug: https://github.com/ossf/scorecard-action/issues/900
This is causing the `main` build to fail.
> Revert "Bump ossf/scorecard-action from 1.1.2 to 2.0.0"

- .github/workflows/scorecards-analysis.yml
Adds the `id-token: write` permission as required by v2.
> Manually update scorecard action to v2.0.3

- platform_design/lib/songs_tab.dart
Replaces an instance of `differenc` with `different` in the platform design sample.
> [platform_design] Fix comment typo.

- experimental/material_3_demo/README.md
- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/test/component_screen_test.dart
Added `Radio` and `ProgressIndicator` to the demo app.
> Add Radios, CircularProgressIndicator and LinearProgressIndicator to the demo app

- simplistic_editor/lib/basic_text_input_client.dart
This PR updates the `simplistic_editor` sample to fix some issues related to `delete` and `backspace` keys.
- On web: before this PR, the `backspace` keys was handled by both the web browser and the framework which leads to a selection state entanglement. (see https://github.com/flutter/samples/issues/1413 and https://github.com/flutter/samples/issues/1450)
- On Desktop: before this PR, the `delete` and `backspace` were not differentiated.
For full context, see https://github.com/flutter/samples/issues/1424#issuecomment-1262738099
Fixes https://github.com/flutter/samples/issues/1450
Fixes https://github.com/flutter/samples/issues/1413
> [simplistic_editor] - Fix delete key on desktop and backspace key on Web

- web/samples_index/pubspec.yaml
The [2.1.5](https://pub.dev/packages/sass_builder/changelog#215) release has a change that was required by newer versions of the sass package. 
Since we still override the sass version due to mdc_web needing to be updated, our version of sass is no longer compatible with new versions of sass_builder, resulting in errors if we upgrade. This PR solves this for now, by limiting sass_builder to v2.1.4. In the long run, we should investigate getting mdc_web updated so we can upgrade sass as well.
> Restrict sass_builder to v2.1.4 to fix build

- platform_channels/lib/src/pet_list_screen.dart
Fixes exception in platform_channels
Related issue:  https://github.com/flutter/samples/issues/1479
> Fixes exception in platform_channels

- web/samples_index/pubspec.yaml
- web/samples_index/tool/grind.dart
tuneup has been discontinued as much of the functionality can be handled by built-in `dart` tools. For `check` we can just replace with direct usage of the analyzer.
Supersedes https://github.com/flutter/samples/pull/1496
> Replace tuneup in samples_index

- game_template/lib/src/level_selection/level_selection_screen.dart
- game_template/lib/src/main_menu/main_menu_screen.dart
- game_template/lib/src/play_session/play_session_screen.dart
- game_template/lib/src/win_game/win_game_screen.dart
- game_template/pubspec.yaml
Mixing declarative (`.go()`) and imperative (`.pop()`) navigation no longer works.
This CL changes all navigation to the declarative `go()` wherever possible. The only imperative navigation still standing is the `/settings` route, which needs to be accessed (pushed) from both the main screen and the play session screen, and therefore there is no single URL to go back to. So we’re keeping `push()` / `pop()` there.
I’m sure it’s possible to implement even the `/settings` route with declarative navigation, but it seems way beyond the scope of this sample.
Fixes #1514. …
> Fix go_router navigation

- animations/lib/main.dart
- animations/lib/src/basics/01_animated_container.dart
- animations/lib/src/basics/02_page_route_builder.dart
- animations/lib/src/basics/03_animation_controller.dart
- animations/lib/src/basics/04_tweens.dart
- animations/lib/src/basics/05_animated_builder.dart
- animations/lib/src/basics/06_custom_tween.dart
- animations/lib/src/basics/07_tween_sequence.dart
- animations/lib/src/basics/08_fade_transition.dart
- animations/lib/src/misc/animated_list.dart
- animations/lib/src/misc/animated_positioned.dart
- animations/lib/src/misc/animated_switcher.dart
- animations/lib/src/misc/card_swipe.dart
- animations/lib/src/misc/carousel.dart
- animations/lib/src/misc/curved_animation.dart
- animations/lib/src/misc/expand_card.dart
- animations/lib/src/misc/focus_image.dart
- animations/lib/src/misc/hero_animation.dart
- animations/lib/src/misc/physics_card_drag.dart
- animations/lib/src/misc/repeating_animation.dart
- animations/pubspec.yaml
In this PR, I am replacing the named routes implementation in the `animations` sample for one using `go_router`.
The codelab_rebuild.yaml would need to be updated to add the go_router installation step.
cc. @domesticmouse @RedBrogdon 
> Migrate animations to go_router

- analysis_options.yaml
- web/samples_index/analysis_options.yaml
The strong mode options were already deprecated and are [being removed](https://github.com/dart-lang/sdk/commit/ea120b5d441edd0803e8313b2a1f706db793c855) in Dart 3.
> Move to using analyzer strict modes instead of deprecated strong mode

- tool/flutter_ci_script_master.sh
> Elide `web_dashboard` from Master CI

- testing_app/lib/main.dart
- testing_app/lib/screens/favorites.dart
- testing_app/lib/screens/home.dart
- testing_app/pubspec.yaml
- testing_app/test/home_test.dart
Migrated the testing_app sample to go_router.
Added a navigation unit test as well.
cc. @domesticmouse 
> Migrate testing_app to go_router

- provider_shopper/lib/main.dart
- provider_shopper/lib/screens/catalog.dart
- provider_shopper/lib/screens/login.dart
- provider_shopper/pubspec.yaml
- provider_shopper/test/login_widget_test.dart
Migrated provider_shopper to go_router.
The routes have been rearranged this way:
- `/` has been moved to `/login`. Also, `/login` is the initial route.
- `/cart` has been moved to `/catalog/cart`, so it follows the route path logic.
cc. @domesticmouse 
> migrate provider_shopper to go_router

- experimental/material_3_demo/lib/color_palettes_screen.dart
- experimental/material_3_demo/lib/component_screen.dart
Introduce a few `RepaintBoundary`s in strategic locations to minimize the size of canvases allocated by Flutter Web.
This PR is an attempt to help with this: https://github.com/flutter/flutter/issues/117164
> Avoid allocation of large canvases on the web

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/test/component_screen_test.dart
This PR is to update the layout of the M3 demo app when it is running on a narrow screen (phone devices).
On iPhone 8 (screen width: 375):
https://user-images.githubusercontent.com/36861262/211948833-3dbed76e-9e8d-4a45-9ae1-e42c97137782.mov
On a 16-inch laptop:
On a 32-inch monitor (future improvement: create a 3-column grid view so that more components can show up and the list can scroll together. And welcome for any other suggestions:) )
> Update M3 demo app layout on small screen

- experimental/varfont_shader_puzzle/analysis_options.yaml
- experimental/varfont_shader_puzzle/lib/components/components.dart
- experimental/varfont_shader_puzzle/lib/components/fragment_shaded.dart
- experimental/varfont_shader_puzzle/lib/components/lightboxed_panel.dart
- experimental/varfont_shader_puzzle/lib/components/rotator_puzzle.dart
- experimental/varfont_shader_puzzle/lib/components/wonky_char.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_ascender_descender.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_narrative_post.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_narrative_pre.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_optical_size.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_weight.dart
- experimental/varfont_shader_puzzle/lib/page_content/page_width.dart
- experimental/varfont_shader_puzzle/lib/page_content/pages.dart
- experimental/varfont_shader_puzzle/lib/page_content/pages_flow.dart
- experimental/varfont_shader_puzzle/lib/styles.dart
> Fixup `varfont_shader_puzzle`, attempt #2

- provider_shopper/lib/screens/login.dart
Fixed text on provider_shopper login button being invisible.
Previous version had yellow text on a yellow button due to use of foregroundColor instead of backgroundColor.
fixed issue: #1559
> fix: provider_shopper login button invisible text

- experimental/web_dashboard/lib/src/api/api.dart
> `experimental/web_dashboard` fix for deprecated annotations

- experimental/context_menus/test/email_button_page_test.dart
> Fix and reenable context_menus email button test

- experimental/material_3_demo/lib/component_screen.dart
This PR is to add a menu example when the "more" button on the bottom app bar is clicked. 
This PR also changes the layout of the common buttons to three columns.
> Add a menu example to show menu system

- experimental/context_menus/test/anywhere_page_test.dart
- experimental/context_menus/test/cascading_menu_page_test.dart
- experimental/context_menus/test/custom_buttons_page_test.dart
- experimental/context_menus/test/custom_menu_page_test.dart
I was getting some weird flaky behavior from these tests that used dragUntilVisible.  As fixed by @parlough in https://github.com/flutter/samples/pull/1585, this was because of a missing pumpAndSettle.  I've added them to other tests here to avoid problems in the future.
> Context Menu sample missing pumpAndSettle

- animations/lib/main.dart
- animations/lib/src/basics/06_custom_tween.dart
- animations/lib/src/misc/animated_switcher.dart
Enable Material 3 on Animations sample.
A couple of AppBar MaterialButtons have been replaced by TextButton.
> Enable Material 3 on Animations sample

- android_splash_screen/lib/main.dart
Enable Material 3 on android_splash_screen sample
> enable Material 3 on android_splash_screen sample

- desktop_photo_search/material/lib/main.dart
Enabled Material 3 on the desktop_photo_search sample. There's another sample that uses FluentUI, which remains the same.
> enable material 3 on desktop_photo_search sample

- code_sharing/client/lib/main.dart
Enable Material 3 on code_sharing sample. The UI is a simple counter app.
> Enable Material 3 on code_sharing sample

- add_to_app/android_view/flutter_module_using_plugin/lib/main.dart
- Enabled Material 3 on add_to_app/flutter_module_using_plugin.
- Changed `ElevatedButton` by `FilledButton`
> Enable Material 3 on add_to_app/flutter_module_using_plugin

- flutter_maps_firestore/lib/main.dart
Enabling Material 3 on flutter_maps_firestore sample.
A bit complicated to have this sample up and running, somehow I was unable to get images from the maps API, I may report this one to the maps plugin repo.
I'm not super-convinced about the color scheme, but that's just how Material 3 is.
> enable material 3 on flutter_maps_firestore

- game_template/lib/main.dart
- game_template/lib/src/level_selection/level_selection_screen.dart
- game_template/lib/src/main_menu/main_menu_screen.dart
- game_template/lib/src/play_session/play_session_screen.dart
- game_template/lib/src/settings/settings_screen.dart
- game_template/lib/src/win_game/win_game_screen.dart
Migrated game_template to Material 3
Basically, the only thing that changes is the `ElevatedButton` that has been replaced by a `FilledButton`.
> Migrate game_template to Material 3

- infinite_list/lib/main.dart
Migrated infinite_list to Material 3
> migrate infinite_list to Material 3

- tool/flutter_ci_script_master.sh
This is a break fix. 
Context: https://github.com/flutter/samples/issues/1616
> Elide `simplistic_editor` from `master` channel

- form_app/lib/main.dart
- form_app/lib/src/validation.dart
Migrated form_app to Material 3
> Migrate form_app to Material 3

- simplistic_editor/lib/basic_text_input_client.dart
- tool/flutter_ci_script_master.sh
The new `insertContent` method is for rich content such as images from Android, so it doesn't seem like something a "simplistic" editor needs to handle for now. Including `TextInputClient` as a mixin allows us to incorporate its empty implementation of `insertContent`. This has the benefit of the sample working on both `stable` and `master`.
Fixes https://github.com/flutter/samples/issues/1616
> Mixin `TextInputClient` to include `insertContent` implementation

- isolate_example/lib/data_transfer_page.dart
- isolate_example/lib/main.dart
Migrated isolate_example to Material 3.
In one case the button text color was changed to offer a bit more contrast, otherwise the rest of the app remains the same.
> Migrate isolate_example to Material 3

- jsonexample/lib/main.dart
Enabled Material 3 on the jsonexample project.
> enable Material 3 on jsonexample

- provider_shopper/lib/common/theme.dart
- provider_shopper/lib/screens/cart.dart
Enabled Material 3 on provider_shopper.
Small change with the checkout 'BUY' button to FilledButton for major contrast.
</details>
</details>
> Enable Material 3 on `provider_shopper`

- provider_counter/lib/main.dart
Enable Material 3 on the provider_counter sample.
UI is the counter app.
> Enable Material 3 on `provider_counter`

- platform_view_swift/lib/main.dart
Migrated platform_view_swift to Material 3
</details>
</details>
> Migrate `platform_view_swift` to Material 3

- experimental/federated_plugin/federated_plugin/example/lib/main.dart
- experimental/federated_plugin/federated_plugin/example/test/widget_test.dart
Enabled Material 3 on `federated_plugin`.
</details>
</details>
> Enable Material 3 on `federated_plugin`

- experimental/linting_tool/lib/theme/app_theme.dart
Enabled Material 3 on `linting_tool`.
</details>
</details>
> Enable Material 3 on `linting_tool`

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/lib/main.dart
- material_3_demo/lib/component_screen.dart
- material_3_demo/lib/main.dart
This PR includes these changes:
* Remove a duplicate `MaterialApp`
* Refactor magic numbers relating to sizing into constants
* Fix `Focus` handling for the app, in particular, to make it easier to focus on elements (b/267773244). Focus now starts logically with navigation and options, then onto components, grouped by list, then by component group. A user can tap in a component card to move the focus there rather than tab all the way through the app. This change was tested manually. …
> Improvements to M3 demo app

- add_to_app/prebuilt_module/flutter_module/lib/main.dart
Enabled Material 3 on `add_to_app/prebuilt_module`.
</details>
</details>
> Enable Material 3 on `add_to_app/prebuilt_module`

- add_to_app/plugin/flutter_module_using_plugin/lib/main.dart
Enabled Material 3 on `add_to_app/plugin`.
</details>
</details>
> Enable Material 3 on `add_to_app/plugin`

- add_to_app/multiple_flutters/multiple_flutters_module/lib/main.dart
Enabled Material 3 on `add_to_app/multiple_flutters`.
In this case, I had to modify a bit the AppBarTheme, so it didn't default to the Material 3 white background and the demo still worked visually.
</details>
</details>
> Enable Material 3 on `add_to_app/multiple_flutters`

- add_to_app/fullscreen/flutter_module/lib/main.dart
Enabled Material 3 on `add_to_app/fullscreen`.
</details>
</details>
> Enable Material 3 on `add_to_app/fullscreen`

- add_to_app/books/flutter_module_books/lib/main.dart
Enabled Material 3 on `add_to_app/books`.
</details>
</details>
> Enable Material 3 on `add_to_app/books`

- material_3_demo/.metadata
- material_3_demo/macos/Runner.xcodeproj/project.pbxproj
- material_3_demo/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- material_3_demo/macos/Runner.xcworkspace/contents.xcworkspacedata
- material_3_demo/macos/RunnerTests/RunnerTests.swift
In https://github.com/flutter/samples/pull/1615 updates were applied to the Material 3 demo that included the updated macOS Podfile from the macOS app template. However, the app template itself had recently been updated to refer to a new target (RunnerTests) in the default Xcode project template that allows for authoring tests of the bits of the Flutter application implemented in Swift. This adds the missing RunnerTests bits to the Xcode project file by copying those over from the app template.
[Contributors …
> [Material3] Add RunnerTests target for macOS

- simple_shader/lib/main.dart
- simple_shader/pubspec.yaml
Trying out `flutter_shaders` to simplify the code. Thoughts?
> `simple_shader`: Utilise `flutter_shaders`

- simplistic_editor/lib/basic_text_input_client.dart
Fixes #1648
This changes sends the caret rect and composing rects to the `TextInputPlugin` to be able to correctly position the IME candidate menu.
> [Simplistic_Editor] Fix IME Candidate Menu on macOS/web

- simplistic_editor/lib/basic_text_input_client.dart
Fixes #1679
This change defines `performSelector` to be able to process keyboard text editing intents coming from the `macOS` `TextInputPlugin`. I also removed the `Shortcuts` widget local to `BasicTextInputClient` so it can inherit `DefaultTextEditingShortcuts`.
> [Simplistic_Editor] Fix keyboard shortcuts on macOS

- experimental/context_menus/README.md
- experimental/context_menus/lib/main.dart
- tool/flutter_ci_script_stable.sh
Support for context menus on the web was added in https://github.com/flutter/flutter/issues/119184.  This PR enables support in these examples.
Closes https://github.com/flutter/samples/issues/1685
> Enable the context menu examples on web

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/test/component_screen_test.dart
- tool/flutter_ci_script_stable.sh
This PR is to update different types of IconButtons by using factory methods: IconButton.filled, IconButton.filledTonal, and IconButton.outlined. It also adds time picker and date picker examples in the Selection card.
This change is only for experimental demo app.
> Update experimental M3 demo

- .github/workflows/beta.yml
- .github/workflows/main.yml
The JDK 12 builds haven't been supported since late 2019. This PR updates CI to use the latest LTS release of the JDK, 17.
Closes #1293
> Update to JDK 17 (latest lts) in CI

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/test/component_screen_test.dart
This PR is to add an example for `SearchAnchor` widget.
> Add a SearchAnchor example to experimental demo

- animations/lib/src/basics/animated_builder.dart
- animations/test/basics/animated_builder_test.dart
This replaces the planned to be deprecated [MaterialButton](https://master-api.flutter.dev/flutter/material/MaterialButton-class.html) with [ElevatedButton](https://master-api.flutter.dev/flutter/material/ElevatedButton-class.html).
| Before | After |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/230678932-7f0c08fd-4816-48c2-9791-db860827fda7.gif" height="450" /> | <img src="https://user-images.githubusercontent.com/48603081/230678928-bebd5b48-82d6-4e3c-a17e-05c0512ba773.gif" height="450" /> |
[Discord]: …
> Replace `MaterialButton` in the `AnimatedBuilder` sample

- desktop_photo_search/fluent_ui/lib/src/widgets/photo_details.dart
Change the deprecated use of `TextButton` to `HyperlinkButton` in `fluent_ui` sample.
The error was:
```
Analyzing fluent_ui...
info - lib/src/widgets/photo_details.dart:40:45 - 'TextButton' is deprecated and shouldn't be used. Deprecated in 4.4.3. Use HypelinkButton instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
info - lib/src/widgets/photo_details.dart:48:45 - 'TextButton' is deprecated and shouldn't be used. Deprecated in 4.4.3. Use HypelinkButton instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
``` …
> Change deprecated TextButton to HyperlinkButton

- experimental/material_3_demo/lib/component_screen.dart
One line change to show the drag handle on the `ModalBottomSheetRoute`.
> Set `showDragHandle` to true for `BottomSheet`

- .github/dependabot.yaml
This configures dependabot to check for out-of-date NPM packages weekly instead of daily, and limits it to direct dependencies. There could be more we could do if we dig through the [Configuration options for the dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) documentation.
cc: @ditman 
fixes #1809
> Reduce dependabot pull requests for web_embedding

- experimental/material_3_demo/lib/component_screen.dart
- experimental/material_3_demo/lib/home.dart
- material_3_demo/lib/component_screen.dart
- material_3_demo/lib/home.dart
Fixes #1694
This PR is to fix the shaking scrollbar problem. We replace the `ListView`s with `CustomScrollView` and cache the content height to provide a better estimation for the max scroll offset.
Same changes are applied to both Material 3 demo in the root directory and the M3 demo in the `/experimental/`
https://github.com/flutter/samples/assets/36861262/24041a84-64e7-480e-8ea3-0d0811038818
https://github.com/flutter/samples/assets/36861262/9f274109-f698-4522-8316-7c75b2596c8b
> Use SliverList and cache content height

- web/samples_index/lib/src/data.dart
- web/samples_index/lib/src/data.g.dart
- web/samples_index/lib/src/samples.yaml
- web/samples_index/test/samples_index_test.dart
- web/samples_index/test/yaml/single.yaml
I've confirmed that the `links` configuration attribute is indeed unused: https://flutter.github.io/samples/next_gen_u_i_demo.html
Dropping unused configuration sounds like a good move. We can re-introduce it if/when we start displaying the content.
> `web/samples_index` Drop unused `links` attribute from config

- game_template/android/app/build.gradle
- tool/flutter_ci_script_master.sh
flutter.minSdkVersion is 16, which is too low for guaranteed use of google_mobile_ads
> Fix minSdkVersion compile error

- next_gen_ui_demo/lib/main.dart
- next_gen_ui_demo/lib/title_screen_4c/title_screen_ui.dart
- next_gen_ui_demo/lib/title_screen_4d/title_screen_ui.dart
- next_gen_ui_demo/lib/title_screen_4e/title_screen_ui.dart
- next_gen_ui_demo/lib/title_screen_5a/title_screen_ui.dart
- next_gen_ui_demo/lib/title_screen_5b/title_screen_ui.dart
- next_gen_ui_demo/lib/title_screen_6/title_screen_ui.dart
Stop some leaks by disposing old `AnimationController`s.
> `next_gen_ui_demo`: Dispose of old `AnimationController`s

- next_gen_ui_demo/lib/main.dart
Now we can skip to start and end, as well as single step. If only `FloatingActionButton`s could be disabled.
> `next_gen_ui_demo`: Make the tape player analogy complete

- experimental/material_3_demo/lib/component_screen.dart
- material_3_demo/lib/component_screen.dart
This PR adds a null check before showing a SnackBar with the selected time in `component_screen.dart`. Previously, the SnackBar was displayed regardless of whether the selected time was null, which could have caused a null exception. 
*This PR fixes a potential issue where a null exception could be thrown if the selected time was null.*
> Add null safety check before displaying SnackBar

- game_template/README.md
- game_template/ios/Podfile
- game_template/ios/Runner.xcodeproj/project.pbxproj
- game_template/ios/Runner.xcworkspace/contents.xcworkspacedata
- game_template/macos/Podfile
- game_template/macos/Runner.xcodeproj/project.pbxproj
- game_template/macos/Runner.xcworkspace/contents.xcworkspacedata
Deal with build errors that people who’ve had the `game_template` around for some time encounter as plugins upgrade to newer Xcode versions and CocoaPods dependencies.
> Rebuild iOS and macOS targets for `game_template`

- platform_channels/lib/src/method_channel_demo.dart
- tool/flutter_ci_script_beta.sh
- tool/flutter_ci_script_master.sh
- tool/flutter_ci_script_stable.sh
> Re-enable `platform_channels` CI

- animations/lib/main.dart
- code_sharing/client/lib/main.dart
- form_app/lib/main.dart
- infinite_list/lib/main.dart
- isolate_example/lib/main.dart
- jsonexample/lib/main.dart
- navigation_and_routing/lib/main.dart
- provider_counter/lib/main.dart
- provider_shopper/lib/main.dart
- simplistic_calculator/lib/main.dart
- veggieseasons/lib/main.dart
Following the ideas in flutter/website#7798 I have changed the imports needed for Platform and kIsWeb to be explicitly named.
> Explicit import for Platform and kIsWeb

- add_to_app/fullscreen/android_fullscreen/app/build.gradle
- add_to_app/fullscreen/android_fullscreen/build.gradle
- add_to_app/multiple_flutters/multiple_flutters_android/build.gradle
- add_to_app/plugin/android_using_plugin/app/build.gradle
- add_to_app/plugin/android_using_plugin/build.gradle
- add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle
- add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle
- kotlin version to 1.8.22
- remove deprecated kotlin-android-extensions and upgrade dependencies
Running the PR from the flutter/samples repo instead from a fork, so the Firebase device test step runs.
> Fix Android CI

- .github/dependabot.yaml
- desktop_photo_search/fluent_ui/lib/src/widgets/unsplash_search_content.dart
- desktop_photo_search/material/lib/src/widgets/unsplash_search_content.dart
- experimental/linting_tool/lib/model/profiles_store.dart
This PR fixes a [CI breakage](https://github.com/flutter/samples/actions/runs/5362518576/jobs/9729453534):
```console
Analyzing fluent_ui...
info - lib/src/widgets/unsplash_search_content.dart:51:38 - 'getSavePath' is deprecated and shouldn't be used. Use getSaveLocation instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use
1 issue found.
Error: Process completed with exit code 1.
```
> `desktop_photo_search`: `getSavePath` is deprecated

- animations/lib/src/misc/carousel.dart
- experimental/varfont_shader_puzzle/lib/components/wonky_char.dart
- next_gen_ui_demo/lib/assets.dart
- next_gen_ui_demo/lib/common/shader_painter.dart
- next_gen_ui_demo/lib/orb_shader/orb_shader_painter.dart
- next_gen_ui_demo/lib/orb_shader/orb_shader_widget.dart
- next_gen_ui_demo/lib/title_screen_5b/title_screen.dart
- next_gen_ui_demo/lib/title_screen_6/title_screen.dart
- veggieseasons/lib/widgets/close_button.dart
- veggieseasons/lib/widgets/veggie_card.dart
Following the proposal in https://github.com/flutter/website/issues/7798 I have added more explicit and named imports on those places I thought it would make sense.
Let me know what you think.
> adding more named and explicit imports

- experimental/pedometer/README.md
I was tripped up when trying to run the pedometer example because I didn't realize it was a plugin.  The actual example app is in the `example` directory.
In case anyone else is as oblivious as me, this will avoid similar confusion.
Fixes https://github.com/flutter/samples/issues/1595
> Explain the pedometer example directory in its README

- simplistic_editor/lib/basic_text_input_client.dart
- tool/flutter_ci_script_master.sh
This change removes an unused parameter that was recently removed in the `RenderEditable` on the `master` branch https://github.com/flutter/flutter/pull/109114.
Fixes #1923
> Fix master CI for `simplistic_editor`

- tool/flutter_ci_script_beta.sh
Fixing a CI breakage caused by the update of Flutter beta.
> Fix CI by eliding `simplistic_editor`

- tool/flutter_ci_script_master.sh
> Elide `animations` & `jsonexample` from master CI

- experimental/varfont_shader_puzzle/lib/main.dart
Enable Material 3.
Very small differences in the default font weight.
> Enable Material 3 on `experimental/varfont_shader_puzzle`

- experimental/pedometer/example/lib/main.dart
Enable Material 3.
Only the font changes slightly.
> Enable Material 3 on `experimental/pedometer`

- deeplink_store_example/lib/main.dart
Enabling Material 3
Change is very subtle.
> Enable material 3 on `deeplink_store_example`

- experimental/context_menus/lib/main.dart
- experimental/context_menus/lib/platform_selector.dart
> Enable Material 3 on `context_menus`

- navigation_and_routing/lib/src/app.dart
- navigation_and_routing/lib/src/screens/books.dart
- navigation_and_routing/lib/src/screens/settings.dart
Enabled Material 3.
Replaced the `ElevatedButton` to `FilledButton` for better visibility.
Added elevation to the top app bar to add contrast to the top navigation tabs.
> Enable material 3 on `navigation_and_routing`

- experimental/web_dashboard/lib/src/app.dart
- experimental/web_dashboard/lib/src/pages/sign_in.dart
- experimental/web_dashboard/lib/src/widgets/category_forms.dart
- experimental/web_dashboard/lib/src/widgets/edit_entry.dart
Enabled Material 3.
Replaced the `ElevatedButton` by `FilledButton` for better contrast.
> Enable Material 3 in `experimental/web_dashboard`

- experimental/linting_tool/lib/repository/api_provider.dart
- experimental/linting_tool/test/widget_test.dart
In preparation for the linter moving to the SDK, the `rules.json` file is no longer generated to its own location. The site-www version is better guaranteed to be up to date and match the `stable` release of Dart.
> Account for new generated rules.json location in linter tool

- simplistic_calculator/lib/main.dart
Enabled Material 3 in `simplistic_calculator`.
- Tempted to change the `ElevatedButton` to a `FilledButton`, what do you think?
- Also thinking about the new button shape, maybe we should change it to squared buttons?
> Enable Material 3 in `simplistic_calculator`

- background_isolate_channels/lib/main.dart
Enabling Material 3 on `background_isolate_channels` sample
> Enable Material 3 on `background_isolate_channels`

- web_embedding/element_embedding_demo/lib/main.dart
Enable Material 3 in `web_embedding` sample
The app shows an embedded "counter sample" inside a website.
> Enable Material 3 in `web_embedding`

- experimental/pedometer/README.md
- experimental/pedometer/example/README.md
- Fixes links to specific files/folders
- Adds more file links where relevant
- Uses more specific link text than "here"
- Add links to relevant apps when mentioned
- Slightly expands on some instructions
- Cleans up formatting
Fixes https://github.com/flutter/samples/issues/1978
> [pedometer] Fix file/folder links and cleanup instructions

- experimental/pedometer/example/pubspec.yaml
- experimental/pedometer/jnigen.yaml
- experimental/pedometer/lib/health_connect.dart
- experimental/pedometer/pubspec.yaml
- experimental/pedometer/src/health_connect/dartjni.h
- experimental/pedometer/src/health_connect/health_connect.c
Updated `package:jni` and `package:jni` in experimental/pedometer to 0.6.1 and 0.6.0 (latest versions) and regenerated the bindings.
> [experimental/pedometer] Update jni and jnigen to 0.6

- isolate_example/lib/infinite_process_page.dart
- place_tracker/lib/place_map.dart
- tool/flutter_ci_script_master.sh
This PR replaces `ButtonBar` with `OverflowBar` in preparation of `ButtonBar` deprecation
related to https://github.com/flutter/flutter/issues/127955
> Replace `ButtonBar` with `OverflowBar`

- web_embedding/element_embedding_demo/web/css/style.css
I was using the embedding sample for an unrelated reason, and found that when using the "rotation" feature, scrollbars would show up all over the place (something changed with regards to `perspective`, maybe?).
This PR addresses the issue.
> [web_embedding] Fix scrollbars on embedding sample.

- web/samples_index/lib/src/samples.yaml
Reorganizes the samples index to deprioritize the gallery in favor of some recent web demos, particularly the Material 3 demo.
This PR does keep the gallery in the index, as it is no more out of date than other samples and there are plans to retire this index. It however updates its demo link to a new Firebase destination that will remain hosted for posterity. 
Closes https://github.com/flutter/samples/issues/2139
> Adjust Flutter gallery inclusion in samples index

- ios_app_clip/README.md
- ios_app_clip/ios/Flutter/AppFrameworkInfo.plist
- ios_app_clip/ios/Podfile
- ios_app_clip/ios/Runner.xcodeproj/project.pbxproj
- ios_app_clip/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- ios_app_clip/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios_app_clip/ios/Runner/AppDelegate.swift
- ios_app_clip/ios/Runner/Info.plist
1. Run `flutter run` on the project to pick up project automigrations.
2. Set min version to iOS 16 to take advantage of the 15MB size limit (see https://github.com/flutter/flutter/issues/71098#issuecomment-1358152892)
3. Other updates needed to avoid Xcode errors and warnings.
First introduced in #538
See also https://github.com/flutter/website/pull/10145
> Update App Clip for Xcode 15 and iOS 16+

- form_app/README.md
This is a simple PR which adds [tunnelmole](https://tunnelmole.com/docs) as a free and open source tunneling option for the form_app sample.
> Add Tunnelmole as a FOSS tunneling tool for the form_app sample

- material_3_demo/lib/color_palettes_screen.dart
- material_3_demo/lib/home.dart
- material_3_demo/test/color_screen_test.dart
This PR is to fix #2289 and add newly added `ColorScheme` roles since https://github.com/flutter/flutter/pull/144273
> Update `ColorScheme` to show the newly added color roles

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- desktop_photo_search/fluent_ui/README.md
- desktop_photo_search/material/README.md
Part of https://github.com/flutter/flutter/issues/145009
> Update old wiki links

- web_embedding/element_embedding_demo/pubspec.yaml
- web_embedding/element_embedding_demo/web/css/style.css
- web_embedding/element_embedding_demo/web/index.html
Migrating the Angular sample is blocked on https://github.com/flutter/flutter/issues/149443
Contributes to https://github.com/flutter/samples/issues/2297.
> Migrate bootstrapping in element embedding sample

- ai_recipe_generation/pubspec.yaml
- dynamic_theme/pubspec.yaml
- experimental/linting_tool/pubspec.yaml
- gemini_tasks/pubspec.yaml
fixes: https://github.com/flutter/samples/issues/2332
> Bump `flutter_markdown` version to latest

- compass_app/app/lib/data/repositories/booking/booking_repository.dart
- compass_app/app/lib/data/repositories/booking/booking_repository_local.dart
- compass_app/app/lib/data/repositories/booking/booking_repository_remote.dart
- compass_app/app/lib/data/services/api/api_client.dart
- compass_app/app/lib/domain/models/booking/booking.dart
- compass_app/app/lib/domain/models/booking/booking.freezed.dart
- compass_app/app/lib/domain/models/booking/booking.g.dart
- compass_app/app/lib/ui/core/localization/applocalization.dart
- compass_app/app/lib/ui/home/view_models/home_viewmodel.dart
- compass_app/app/lib/ui/home/widgets/home_screen.dart
- compass_app/app/test/data/repositories/booking/booking_repository_remote_test.dart
- compass_app/app/test/data/services/api/api_client_test.dart
- compass_app/app/test/ui/home/widgets/home_screen_test.dart
- compass_app/app/testing/fakes/repositories/fake_booking_repository.dart
- compass_app/app/testing/fakes/services/fake_api_client.dart
- compass_app/app/testing/mocks.dart
- compass_app/server/lib/routes/booking.dart
- compass_app/server/pubspec.yaml
- compass_app/server/test/server_test.dart
This PR adds the swipe-to-delete functionality on the home screen.
To properly handle this, I had to change how booking IDs work (otherwise the `Dimissable` widget would not like it). Now, IDs are generated sequentially, either by the local Bookings repository or by the server.
https://github.com/user-attachments/assets/523cb786-f2ab-4c57-b241-23901eee76b1
(it's the same video I shared yesterday) …
> [Compass App] Swipe to delete bookings

- material_3_demo/android/app/src/main/kotlin/com/example/material_3_demo/MainActivity.kt
- material_3_demo/android/app/src/main/res/values/styles.xml
Edge to edge is coming by default to Flutter 3.26+ (or thereabouts) when the targetSdk is raised to Android 15(API 35). In the meantime, it can be done manually by adjusting the theme and setting `WindowCompat.setDecorFitsSystemWindows`.
The fix is purely on the Android side. iOS is unaffected.
Sourced from https://developer.android.com/develop/ui/views/layout/edge-to-edge-manually
Fixes #1720 . …
> m3_demo - Enables edge to edge support.

- material_3_demo/lib/color_box.dart
- material_3_demo/lib/color_palettes_screen.dart
- material_3_demo/lib/scheme.dart
- material_3_demo/lib/typography_screen.dart
- material_3_demo/test/color_screen_test.dart
- tool/flutter_ci_script_beta.sh
- tool/flutter_ci_script_master.sh
- Added the color scheme schematic from Material Theme Builder aligning how colors are displayed here and in documentation across Android and Figma.
- On desktop, individual colors can be copied to the clipboard
- View adapts from the existing single column view to the new schematic at 500dp width.
> Improve color display in M3 Demo

- compass_app/app/lib/config/dependencies.dart
- compass_app/app/lib/domain/use_cases/booking/booking_create_use_case.dart
- compass_app/app/lib/domain/use_cases/booking/booking_share_use_case.dart
- compass_app/app/lib/routing/router.dart
- compass_app/app/lib/ui/auth/logout/view_models/logout_viewmodel.dart
- compass_app/app/lib/ui/booking/view_models/booking_viewmodel.dart
- compass_app/app/test/domain/use_cases/booking/booking_create_use_case_test.dart
- compass_app/app/test/domain/use_cases/booking/booking_share_use_case_test.dart
- compass_app/app/test/ui/booking/booking_screen_test.dart
We decided it was better to use the common term 'use case'.  This PR updates the names of files, classes and several variables.
> Rename components to use cases. 

- compass_app/app/lib/ui/home/widgets/home_screen.dart
- compass_app/app/test/ui/home/widgets/home_screen_test.dart
Doing some testing on the "Optimistic State" I noticed the use of `Dismissable` was incorrect.
If the delete request failed and the item cannot be removed, the removed item then gets stays in the item list.
This causes the `Dismissable` widget to throw an exception, because it expects that the item with a unique key has been removed. To fix that, I switched from `onDismissed` to `confirmDismiss`, and use the `Command` status result to know if the dismiss action was successful or not.
I have created a widget test that reproduces the issue. …
> fix: compass-app bug in dismissable homescreen item

- material_3_demo/lib/color_box.dart
- material_3_demo/lib/component_screen.dart
- material_3_demo/lib/scheme.dart
Added copyright license to newly added files from recent PR to m3 demo.
Minor tweak to component bumping the text label in Component decoration from titleSmall to titleMedium. See ___ Buttons label in below screen shot
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr><td>Before</td><td>After</td></tr>
</table>
> Adding copyright license to recently added files. Minor text label tweak. 

- CONTRIBUTING.md
Update contributing guidelines to reflect new policies for 2025.
Related to #2497, but does not complete it.
> Update contributing guidelines for repository

- compass_app/app/lib/data/repositories/auth/auth_repository_dev.dart
- compass_app/app/lib/data/repositories/booking/booking_repository_local.dart
- compass_app/app/lib/data/repositories/itinerary_config/itinerary_config_repository_memory.dart
- compass_app/app/lib/data/services/api/api_client.dart
- compass_app/app/lib/data/services/api/auth_api_client.dart
- compass_app/app/lib/data/services/shared_preferences_service.dart
- compass_app/app/lib/domain/use_cases/booking/booking_create_use_case.dart
- compass_app/app/lib/domain/use_cases/booking/booking_share_use_case.dart
- compass_app/app/lib/ui/booking/view_models/booking_viewmodel.dart
- compass_app/app/lib/utils/result.dart
- compass_app/app/testing/fakes/services/fake_auth_api_client.dart
From my review of the recipes PR in https://github.com/flutter/website/pull/11444#pullrequestreview-2480423811.
> [compass_app] Standardize on `Result` factories rather than constructors

- compass_app/app/lib/config/assets.dart
- compass_app/app/lib/routing/routes.dart
- compass_app/app/lib/ui/core/themes/colors.dart
- compass_app/app/lib/ui/core/themes/theme.dart
- compass_app/server/lib/config/assets.dart
- compass_app/server/lib/config/constants.dart
As they are just used for namespacing static properties, these classes shouldn't be extended, implemented, or instantiated.
> [compass_app] Mark classes used for namespacing as `abstract final`

- compass_app/app/lib/ui/core/themes/dimens.dart
- compass_app/app/lib/ui/results/widgets/results_screen.dart
Avoid exposing the subclasses as they shouldn't be instantiated again or overridden.
Also consistently use fields and getters in the declarations.
> [compass_app] Don't expose Dimens subclasses

- CONTRIBUTING.md
This is a follow on PR from https://github.com/flutter/samples/pull/2532
> Fixup internal links in `CONTRIBUTING.md`

- context_menus/README.md
Fix broken references in the README.md.
> Update content_menus README.md references

- web/_tool/fix_base_tags.dart
We use the hosted artifacts, so this just wastes storage
> [web] when building examples, delete the canvaskit bits from the output

- add_to_app/plugin/android_using_plugin/app/build.gradle
- add_to_app/plugin/android_using_plugin/build.gradle
- add_to_app/plugin/android_using_plugin/gradle/wrapper/gradle-wrapper.properties
- add_to_app/prebuilt_module/android_using_prebuilt_module/app/build.gradle
- add_to_app/prebuilt_module/android_using_prebuilt_module/build.gradle
- add_to_app/prebuilt_module/android_using_prebuilt_module/gradle/wrapper/gradle-wrapper.properties
- **update AGP and gradle versions**
- **[prebuilt_module] update agp and gradle**
- **[prebuilt_module] targetsdk and jvm compatabiliity**
Fixes flutter/flutter/152374
> Update android samples to target/compile android 35 and AGP/Gradle updates

- compass_app/app/lib/ui/auth/login/widgets/login_screen.dart
*- use SingleChildScrollView in the auth screen to fix pixel overflowed.*
*Fix for: https://github.com/flutter/samples/issues/2668.*
> [compass_app] fixing pixel overflowed
